plugin-worldclock/lxqtworldclockconfiguration.cpp, plugin-worldclock/lxqtworldclockconfiguration.h
When the Date checkbox is unchecked the dateCustomW group should be
disabled.
=> worldclock: Fix Ui date settings load inconsistency

CMakeLists.txt, cmake/BuildPlugin.cmake, panel/CMakeLists.txt, panel/plugin.cpp, panel/plugin.h, plugin-clock/lxqtclock.h, plugin-desktopswitch/desktopswitch.h, plugin-mainmenu/lxqtmainmenu.h, plugin-quicklaunch/lxqtquicklaunchplugin.h, plugin-showdesktop/CMakeLists.txt, plugin-showdesktop/showdesktop.h, plugin-taskbar/lxqttaskbarplugin.h, plugin-tray/CMakeLists.txt, plugin-tray/lxqttrayplugin.h
Make some frequently used plugins "statically-linked" to speed up plugin loading.
The static plugins are: clock, desktopswitch, mainmenu, quicklaunch, showdesktop, taskbar, tray, and worldclock.
They'll be statically linked into lxqt-panel and have no *.so modules.
Binary search is used internally for plugin name matching.
This is a relatively larger change so I hope more developers can help the review.
Only few lines of source code are changed, though.
@luis-pereira, @paulolieuthier @jleclanche @kuzmas @surlykke @agaida 
Thanks!
=> Make some frequently used plugins "statically-linked" to speed up loading.

plugin-mount/mountbutton.cpp
Using more than one icon can lead to icons not being show, depending on the
theme set when XdgIcon::fromTheme() is executed, although it may exits on
the theme.
QIconloaderEngine only stores the icon it founded when XdgIcon::fromTheme()
was executed. When the theme changes QIconLoader will only search for the
icon name it stored when XdgIcon::fromTheme() was executed.
=> plugin-mount: Use only one icon instead a list of possible ones

plugin-tray/CMakeLists.txt
Without this package, make will fail on plugin-tray/lxqttray.h because xcb/xcb_event.h is missing.
I have tried this on Ubuntu 14.10. I think this could be merged without any problems.
=> Add required package xcb-util to plugin-tray

plugin-desktopswitch/desktopswitch.cpp, plugin-desktopswitch/desktopswitch.h, plugin-desktopswitch/desktopswitchbutton.cpp, plugin-desktopswitch/desktopswitchbutton.h, plugin-desktopswitch/desktopswitchconfiguration.cpp, plugin-desktopswitch/desktopswitchconfiguration.h, plugin-desktopswitch/desktopswitchconfiguration.ui
(note: includes PR #155 since that's what I was working on initially)
This is a work in progress but basically what it does is:
* initially create the button in the `DesktopSwitch` constructor
* create and delete buttons in `onNumberOfDesktopChanged` if needed
* refresh by modifying existing buttons
The performance difference is obvious for everything that needs a refresh (adding/deleting desktops or changing the configuration), it took 2 to 3 seconds to refresh and now it's basically instantaneous. And there probably still are a lots of call to refresh that could be avoided.
I haven't really looked at the shortcuts yet, so it's very likely that as of right now this PR breaks them.
=> plugin-desktopswitch: refactoring and optimizations

panel/lxqtpanel.cpp, panel/lxqtpanel.h, panel/plugin.h
references lxde/lxqt#536, lxde/lxqt#552 (and maybe others)
Added support for manaing of widgets in the old "add plugin dialog" -> just forward the context menu for each one to the dialog.
Note: must be merged right after lxde/liblxqt#38
=> panel: widgets manageable from "add plugin dialog"

plugin-volume/ossengine.cpp
sys/soundcard.h is an OSS (Linux) audio emulator
=> Fix NetBSD build

plugin-taskbar/lxqttaskbar.cpp
Don't stretch the taskbar's buttons along the panel in `IconOnly` mode. It avoids having a big button with only a small icon in the middle.
=> plugin-taskbar: don't stretch along the panel in icon only

panel/lxqtpanel.cpp
lxqt-panel is not always resized and repositioned correctly after applying a monitor configuration (e.g. changing screen's resolution). Apparently, that's a bug in Qt. The panel listened to `QDesktopWidget::resized` signal, which was not always emitted. Making it listen to the `workAreaChanged` signal seems to solve the problem.
This is an attempt to fix issues like lxde/lxqt#650 and lxde/lxqt#520. Reading `QDesktopWidget`'s [source](https://github.com/qtproject/qtbase/blob/5.4.2/src/widgets/kernel/qdesktopwidget.cpp) helped a little, but this needs testing.
@pmattern, @Vladimir-csp and @hduff: please, test this if you can.
The bug I can reproduce is that after changing my screen's resolution repeatedly, lxqt-panel would eventually not reset its size and position, as it should.
=> Improve multi-monitor support

plugin-taskbar/lxqttaskbar.cpp, plugin-taskbar/lxqttaskbar.h, plugin-taskbar/lxqttaskbarconfiguration.cpp, plugin-taskbar/lxqttaskbarconfiguration.ui, plugin-taskbar/lxqttaskgroup.cpp
Adds posibility to have windows arranged by desktop(s) -> multiple taskbar widgets each showing only particular desktop windows. E.g. 3 desktops:
This is a workaround/enhancement for lxde/lxqt#102 and/or lxde/lxqt#641
@Vladimir-csp can you, please, check if this is usable for your needs?
=> plugin-taskbar: show only particular(configurable) desktop windows

plugin-volume/audiodevice.cpp, plugin-volume/audiodevice.h, plugin-volume/audioengine.cpp, plugin-volume/audioengine.h
PulseAudio does not have a simple 0 to 100 volume scale. So dealing with
maximum volume must handle the volumes proportionally.
Fixes lxde/lxqt#252.
=> plugin-volume: handle maximum volume proportionally

panel/lxqtpanel.cpp, panel/lxqtpanel.h
The panel pushes (maximised) windows aside when moving from hidden to shown. A properly behaving panel with auto-hide enabled should appear above all windows, and not beside them; in other words: it should slide above them and not push them aside.
Buggy:
Fixed:
=> Make panel appear above all windows when auto-hide is enabled

plugin-kbindicator/src/content.cpp, plugin-kbindicator/src/kbdstateconfig.cpp, plugin-kbindicator/src/kbdstateconfig.ui, plugin-kbindicator/src/settings.cpp, plugin-kbindicator/src/settings.h, plugin-kbindicator/src/x11/kbdlayout.cpp
This PR fixes lxde/lxqt#735, lxde/lxqt#730, lxde/lxqt#732 and probably lxde/lxqt#731
Settings now looks like:
But i don't know and cannot find why label is orange, anybody knows? :)
=> Kbd state indicator, settings dialog, fixed small issues

plugin-kbindicator/CMakeLists.txt, plugin-kbindicator/kbindicator-plugin.cpp, plugin-kbindicator/src/content.cpp, plugin-kbindicator/src/content.h, plugin-kbindicator/src/controls.h, plugin-kbindicator/src/kbdinfo.h, plugin-kbindicator/src/kbdkeeper.cpp, plugin-kbindicator/src/kbdkeeper.h, plugin-kbindicator/src/kbdlayout.h, plugin-kbindicator/src/kbdstate.cpp, plugin-kbindicator/src/kbdstate.h, plugin-kbindicator/src/kbdstateconfig.cpp, plugin-kbindicator/src/kbdstateconfig.h, plugin-kbindicator/src/kbdwatcher.cpp, plugin-kbindicator/src/kbdwatcher.h, plugin-kbindicator/src/settings.cpp, plugin-kbindicator/src/settings.h, plugin-kbindicator/src/x11/kbdlayout.cpp, plugin-kbindicator/src/x11/kbdlayout.h, plugin-mount/actions/deviceaction.cpp, plugin-mount/actions/deviceaction.h, plugin-mount/actions/deviceaction_info.cpp, plugin-mount/actions/deviceaction_info.h, plugin-mount/actions/deviceaction_menu.cpp, plugin-mount/actions/deviceaction_menu.h, plugin-mount/actions/deviceaction_nothing.cpp, plugin-mount/actions/deviceaction_nothing.h
* LGPL2.1+ for kbindicator plugin (c) 2015 zjes
* mount plugin - text don't match declaration (LGPL2.1+ vs GPL2)
=> some license fixup

plugin-statusnotifier/statusnotifierbutton.cpp, plugin-statusnotifier/statusnotifierwidget.cpp, plugin-statusnotifier/statusnotifierwidget.h
This PR handles:
- correct disposal of objects (avoid memory leaks, make correct unregistration of org.kde.StatusNotfierWatcher on DBus)
- checking for existence of menu (avoid SEGFAULT crash)
- postpone new item registration logic (avoid deadlock/timeout for registering of some clients)
=> Notifier fixes

plugin-colorpicker/colorpicker.cpp, plugin-tray/trayicon.cpp
Qt has deprecated QPixmap::grabWindow, which is still used in the color picker and systray plugins. This commit replaces these calls with the new QScreen::grabWindow.
Fixes lxde/lxqt#826.
Fixes lxde/lxqt#827.
=> Replace QPixmap::grabWindow with QScreen's version

panel/lxqtpanel.cpp, panel/lxqtpanel.h
Do not stay on temporary screen when configured screen reapears.
closes lxde/lxqt#722
=> panel: remeber configured screen

panel/panelpluginsmodel.cpp
In method <tt>PanelPluginsModel::findNewPluginSettingsGroup()</tt> we check first
if there is an instance of the plugin so that we don&rsquo;t start enumerating
plugins from number two when unwarranted.
=> Fix #839 - lxqt-panel plugins enumeration

panel/panelpluginsmodel.cpp
Method PanelPluginsModel::findNewPluginSettingsGroup()
complement to pull request lxde/lxqt-panel#245 related to issue lxde/lxqt#839
=> Optimization on plugin name generation, as suggested by palinek.

panel/lxqtpanel.cpp, panel/lxqtpanel.h, panel/lxqtpanelapplication.cpp, panel/lxqtpanelapplication.h
Any plugin can simply do: `reinterpret_cast<LxQtPanelApplication *>(qApp)->settings()` and put in question the panel's settings' reliability.
See discussion in lxde/lxqt#443.
=> Make panel's settings private for more reliability

plugin-volume/lxqtvolume.cpp, plugin-volume/lxqtvolume.h, plugin-volume/pulseaudioengine.cpp, plugin-volume/pulseaudioengine.h
The add/removal of sink in pulse wasn't handled at all -> the supporing
logic was added into pulse engine.
Setting the default sink in volume plugin was also broken (after
number of sinks changed, the default wasn't correctly restored).
This should be the solution for unusability of plugin-volume for case when pulse sinks are added/removed (e.g. adding/removing hotplug audio device).
@jleclanche I wasn't able to find the issue for this. I was trying to simulate, what you had told yesterday on IRC, by enabling/disabling devices .
=> volume: Handle add/removal of pulse sink correcly

plugin-mainmenu/lxqtmainmenu.cpp, plugin-mainmenu/lxqtmainmenu.h
Globalkeys uses not compatible string representation of shortcut (it's probably done by KeysymToString)
with QKeySequence. So we are not able to know if the shortcut sequence was pressed in event handling.
We use a workaround and closing the menu after any "modifier" key pushed (this way also other QMenu objects behave)
references lxde/lxqt#859
=> mainmenu: Fix close menu by "weird" shortcut

panel/lxqtpanel.cpp
After @fde6b272e2fec87b5567c252bf28fe0348aa9afb calculation of reserved space was broken for
multihead configurations with different particular resolutions.
closes lxde/lxqt#861
=> panel: Fix reserved space on screen

plugin-desktopswitch/desktopswitch.cpp, plugin-desktopswitch/desktopswitch.h
Sometimes a button of the desktop-switch plugin gets hightlighted, but its correspondent window is not in the taskbar plugin. Now the same filter that is applied in the taskbar will be applied in desktop-switch.
=> desktop-switch: Hightlight only windows that are in the taskbar as well

panel/CMakeLists.txt, panel/ilxqtpanel.h, panel/ilxqtpanelplugin.h, panel/lxqtpanel.cpp, panel/lxqtpanel.h, panel/plugin.cpp, panel/windownotifier.cpp, panel/windownotifier.h, plugin-clock/lxqtclock.cpp, plugin-directorymenu/directorymenu.cpp, plugin-dom/domplugin.cpp, plugin-mainmenu/lxqtmainmenu.cpp, plugin-mount/popup.cpp, plugin-statusnotifier/statusnotifierbutton.cpp, plugin-taskbar/lxqttaskgroup.cpp, plugin-volume/volumebutton.cpp, plugin-worldclock/lxqtworldclock.cpp
closes lxde/lxqt#871
I don't know if I catched all the shown standalone windows.... please, check.
Update: closes lxde/lxqt#853
=> Autohide prevent

plugin-worldclock/lxqtworldclock.cpp, plugin-worldclock/lxqtworldclock.h, plugin-worldclock/lxqtworldclockconfigurationmanualformat.ui
Logic changed from "wake-up at least each 100ms and check if there is something to do"
to "wake-up precisely and do what is needed" by use of Qt::PreciseTimer (as in @3af690c).
closes lxde/lxqt#873
=> worldclock: Decrease (unnecessary) wake-ups

panel/lxqtpanel.cpp
Auto filling background is needed for "System" a.k.a. "No Theme"
ref. lxde/lxqt#892
=> panel: Fill background

panel/pluginsettings.h
On some configuration the PluginSettings symbols aren't in dynsym section.
closes lxde/lxqt#928
=> plugin settings: Publish PluginSettings symbols

plugin-taskbar/lxqttaskbar.cpp, plugin-taskbar/lxqttaskbar.h, plugin-taskbar/lxqttaskgroup.cpp, plugin-taskbar/lxqttaskgroup.h
Logic changed to use just one hash Wid -> LXQtTaskGroup* to directly address "button" upon window props change.
=> taskbar: Refactor/improove window handling logic

panel/pluginsettings.cpp
After removal(@456f597) of computation/checking hash for owned keys the settingsChanged() signal
was emitted whenever any setting was changed. That led to unnecessary execution of code in each plugin...
This needs PR lxde/liblxqt#77
~~This one still suffers from delivering the settingsChanged to all plugins if the change was made by external application (e.g. text editor). Should we try to sort this out or is it acceptable?~~
=> Fix settingsChanged() distribution to all plugins if change was made only to one

plugin-mainmenu/lxqtmainmenu.cpp
According to my debuging session...the "freeze" hapens on `(un)polish()` of mainmenu button.
I'm not completely sure why this happens, but removing the `unpolish()` fixes this on my side (and does not harm applying the icon from the theme).
closes lxde/lxqt#955
=> mainmenu: Fix freeze for some widget styles (e.g. breeze)

plugin-mainmenu/lxqtmainmenu.cpp, plugin-spacer/spacer.cpp
Avoiding of QStyle::polish() usage... let the Qt handle it.
@tsujan Thanks for suggestions in #302.  While testing & trying different possibilities I finaly came to this one.
How do you see this? Is it "cleaner/better" ?
=> mainmenu: Use "cleaner" style logic

panel/lxqtpanellayout.cpp
Moving the center of computed rectagnle can lead to unused portions of
space. This was the case for standard (separate) plugins if the iconsize
was big enough to fulfill the space.
see lxde/lxqt#962
=> panellayout: Avoid plugin margins

plugin-colorpicker/colorpicker.cpp, plugin-desktopswitch/desktopswitch.cpp, plugin-dom/domplugin.cpp, plugin-mainmenu/lxqtmainmenu.cpp, plugin-mount/button.cpp, plugin-quicklaunch/quicklaunchbutton.cpp, plugin-screensaver/panelscreensaver.cpp, plugin-showdesktop/showdesktop.cpp, plugin-statusnotifier/statusnotifierbutton.cpp, plugin-volume/volumebutton.cpp
In "system" theme the plugins were not borderless as in all "specific" themes.
=> plugins: Make buttons flat for cleaner look

plugin-mainmenu/lxqtmainmenu.cpp
1. Remove search QLineEdit parentless show on panel start (menu not built yet)
2. Fix changing cursor to edit
see https://github.com/lxde/lxqt/issues/101#issuecomment-204038202
=> mainmenu: Fix visual search problems

panel/lxqtpanel.cpp
It stops the user accidentally removing it.
Closes lxde/lxqt#716.
=> Asks for confirmation when removing a panel

CMakeLists.txt
It makes the '+' will automatically be performed as the QStringBuilder '%'
everywhere.
=> Add QT_USE_QSTRINGBUILDER to the compile definitions

panel/plugin.cpp
The Qt "do not allow unload" patch
(https://codereview.qt-project.org/#/c/140750/) was postponed to Qt5.7
Discussion and agreement on not unloading libraries is here ->
http://lists.qt-project.org/pipermail/development/2015-November/023681.html
So plugins will not be unloadable in future Qt apps.
This solves e.g. mount plugin SEGFAULT described
https://github.com/lxde/lxqt/issues/1013#issuecomment-209793407.
=> plugins: Don't unload -> avoid dangling resources

panel/plugin.cpp
The plugins should only be connected to their settings' reset signal after they have been properly initialized.
Fixes lxde/lxqt#1031.
=> Fix segfault on plugin initialization

CMakeLists.txt
The `-std` option is set on line 18 or line 20; no need to set it twice.
=> Clean up CMakeLists.txt

plugin-statusnotifier/statusnotifierbutton.cpp
As discussed in https://github.com/lxde/lxqt-panel/commit/636838fe2cd9b68da446405c8d2f3b81af16a7e5#commitcomment-17137712.
=> Fix popup position of right click's menu of lxqt-panel's status notifier items

panel/lxqtpanel.cpp
I did a build of QT 5.5.1 on FreeBSD with WITH_DEBUG=YES in /etc/make.conf. This causes the macro Q_ASSERT to be expanded in QT sources. One assert is that the object on which setParent is called, must have isWidget set to a true value, [(1)](http://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/kernel/qobject.cpp?h=v5.5.1#n1932) , which defaults to false [(2)](http://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/kernel/qobject.cpp?h=v5.5.1#n205) for a QObject. After looking at the code, I do not get why the setParent is called. So I removed it, and AFAICT the plugins popUpMenus are  working as intended (without a failing assert on debug builds.)
[1] http://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/kernel/qobject.cpp?h=v5.5.1#n1932
[2] …
=> Remove (extranous?) m->setParent(menu)

panel/plugin.cpp, panel/plugin.h
Using the global (name indexed) map for storing configuration dialogs
of plugins wasn't a good idea:
1. plugins in different panels can (and will) have equal name
2. there's no need to search for existing pointer, when we can store it
directly
So with the old implementation we can end in activativation of dialog
belonging to different plugin in different panel.
Steps to reproduce the old/wrong behaviour:
- create two panels, each with e.g. clock plugin
- in confguration dialog of each panel check, that the names are equal (e.g. `clock`)
- invoke configuration dialog of clock in panel A via the context menu
- try to invoke configuration dialog of clock in panel B via the context menu
=> the pre-existing configuration dialog of clock in panel A will just be shown and the configuration …
=> plugin: Fix crossreferencing of config dialogs

panel/lxqtpanel.cpp
The "Remove panel" string is used both as a menu item (Action) and a dialog title. Arabic translation is diffrent for these two contexts. This will make each string a separate entry in the translation file.
=> Separate a String for I18N Enhancement

plugin-kbindicator/CMakeLists.txt
Add the standard directory.
Without this I get:
```
[   80s] cd "/home/abuild/rpmbuild/BUILD/lxqt-panel-0.10.0~git129.1c48664/build/plugin-mount" && /usr/bin/c++   -DLXQT_DATA_DIR=\"/usr/share\" -DLXQT_ETC_XDG_DIR=\"/etc/xdg\" -DLXQT_GRAPHICS_DIR=\"/usr/share/lxqt/graphics\" -DLXQT_RELATIVE_SHARE_DIR=\"lxqt\" -DLXQT_RELATIVE_SHARE_TRANSLATIONS_DIR=\"lxqt/translations\" -DLXQT_SHARE_DIR=\"/usr/share/lxqt\" -DLXQT_SHARE_TRANSLATIONS_DIR=\"/usr/share/lxqt/translations\" -DLXQT_VERSION=\"0.10.0\" -DPLUGIN_DIR=\"/usr/lib64/lxqt-panel\" -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_XML_LIB -DWITH_CLOCK_PLUGIN -DWITH_DESKTOPSWITCH_PLUGIN -DWITH_MAINMENU_PLUGIN -Dmount_EXPORTS …
```
=> Add XKB_COMMON_INCLUDEDIR

plugin-taskbar/lxqttaskbarconfiguration.ui
With that change maximal button width can be set so big,
that allows to fill taskbar with just one button.
(fluxbox-like)
=> Remove arbitrary limit of taskbar button width

plugin-desktopswitch/desktopswitchbutton.cpp, plugin-desktopswitch/desktopswitchbutton.h, plugin-desktopswitch/desktopswitchconfiguration.ui
When the user doesn't want to show numbers or workspaces names (specially
when using multi row display at the switcher) but want to keep workspaces
names.
A "None" option was added to display no text at the desktop switcher.
Signed-off-by: Bruno Ribas brunoribas@gmail.com
=> plugin-desktopswitch: Add LABEL_TYPE_NONE

plugin-mainmenu/CMakeLists.txt
Improved non standard location detection.
Drop the use of empty entries in LIBRARIES. If MenuCache is not found then
MENUCACHE_LIBRARIES is empty and CMake is picky about it now.
=> Use the new lxqt-build-tools CMake modules (FindMenuCache)

panel/lxqtpanel.cpp, panel/plugin.cpp, panel/plugin.h
The DragLeave event is not delivered to the parent widget while DND and
the cursor leaves the parent and child (which also observes drag
events) simulatenously.
The panel needs to know about the DragLeave event (to correctly hide)
even if there is no spare space between the child plugin and the panel
edge.
So we're observing the DragLeave events for all the plugins and its
children widgets.
---
1. With this we don't need to do anything special in particular plugins.
2. At first look it seemed to me as a bad idea to observe all the children (and its children ..) objects/widgets, but a simple check with `callgrind` is showing zero time spent in the `Plugin::eventFilter()`
3. We probably can't extend this logic to remove the `willShowWindow()` logic, because in case of standalone windows …
=> panel: Hide correctly upon the DragLeave

plugin-sysstat/lxqtsysstatconfiguration.cpp
Setting for maximum network speed wasn't saved on its own (it was saved
only when some other setting was changed).
fixex lxde/lxqt#1249
=> sysstat: Fix saving of network maximum speed

plugin-volume/pulseaudioengine.cpp
While recalculating volume to percentage the result wasn't correctly
rounded. This caused the information held by plugin volume be out of
sync with actual device state.
Then adjusting the volume by plugin-volume behaved strange.
ref lxde/lxqt#1263
=> volume: Fix reporting of pulse volume

plugin-volume/alsadevice.cpp, plugin-volume/alsadevice.h, plugin-volume/alsaengine.cpp
By changing the volume range for alsa mixer we lost the control over
(possible) rounding problems when setting the volume. So setting
volume to particular (mapped) value didn't necessarily result to that
value realy used by alsa (alsa's calculation mapped -> native and
native -> mapped didn't yield the same value).
Then adjusting the volume by plugin-volume sometimes behaved strange.
ref lxde/lxqt#1263
=> volume: Fix calculating of alsa volume

plugin-volume/volumebutton.cpp, plugin-volume/volumebutton.h, plugin-volume/volumepopup.cpp, plugin-volume/volumepopup.h
This is a follow-up of #397 ... after all I think there is no need for the configuration if the `line-per-scroll` should be ignored for the wheel over button or slider...
closes #397 
closes lxde/lxqt#1263
=> Volume fixes

plugin-taskbar/lxqttaskgroup.cpp
Also set a maximum width and elide texts beyond it.
This (probably) needs https://github.com/lxde/lxqt-panel/pull/399 for eliding.
=> Fit the task group to its contents

panel/lxqtpanellayout.cpp, plugin-directorymenu/directorymenu.cpp, plugin-statusnotifier/statusnotifierbutton.cpp, plugin-statusnotifier/statusnotifierwidget.cpp, plugin-volume/volumebutton.cpp
Fixes lxde/lxqt#374
Examples (panel width: 200, icon size: 42):
- before
- after
=> Layout expand items

plugin-mainmenu/lxqtmainmenu.cpp
This only happens to (me) on FreeBSD.  
open menu push escape-> lxqt-panel crash.
open menu press enter -> lxqt-panel crash.
For some reason Debian/Openbox sets the top MenuItem to active on the same userinput so the bug does not happen there.
On Debian
open menu:
QAction(0x00) Inital QMenu::activeMenu
press Enter
QAction(0x1054210 text="Andre" toolTip="Andre" menuRole=TextHeuristicRole visible=true) (Andre = Others)
On FreeBSD [QMenu::activeAction](https://github.com/lxde/lxqt-panel/blob/master/plugin-mainmenu/lxqtmainmenu.cpp#L505)
keeps returning 0 until a MenuItem is manually selected with the mouse.
=> Avoid calling text() in MatchAction on a QAction == 0

panel/resources/panel.conf
In #426 they forgot to change to using worldclock by default instead of clock when they added the deprecation notice. This fixes that.
=> Use worldclock by default instead of clock.

plugin-tray/lxqttray.cpp
plugin-tray can end up with misdrawn tray icons.  The icon you can
interact with may actually draw the icon, or may instead be an empty
space.  Attempting to right click the duplicate yields the
"System tray" menu.
LXQtTray::addIcon() is being double-invoked with the same window id,
which implies a duplicate SYSTEM_TRAY_REQUEST_DOCK client message.
(possible match for https://github.com/lxde/lxqt/issues/1337, unclear from the discussion)
=> plugin-tray: Fix dupe icon display error

plugin-worldclock/lxqtworldclock.cpp
If the content change resulted in need of different size to show all
the content, the parent widget(s) didn't get the change. This resulted
in cut text or waste of space in panel.
ref. lxde/lxqt#1356, lxde/lxqt#632
=> worldclock: Fix widget size updating

plugin-volume/volumepopup.cpp
Some "modern" icon themes have a specific panel icon for volumes.
Arc, deepin, Faenza, Faience, Flattr, matefaenza, Menda-Circle, Numix,
Numix-Light, Numix-uTouch, Paper, Papirus and it's derivatives are examples
of that.
Examle
Before:
After:
=> plugin-volume: Use a specific icon for the panel

CMakeLists.txt, panel/lxqtpanel.cpp, panel/lxqtpanelapplication.cpp, panel/lxqtpanellayout.cpp, panel/plugin.cpp, plugin-directorymenu/directorymenu.cpp, plugin-mainmenu/lxqtmainmenu.cpp, plugin-mainmenu/xdgcachedmenu.cpp, plugin-quicklaunch/lxqtquicklaunch.cpp, plugin-statusnotifier/statusnotifierbutton.cpp, plugin-taskbar/lxqttaskgroup.cpp, plugin-tray/lxqttray.cpp, plugin-volume/alsaengine.cpp, plugin-volume/lxqtvolumeconfiguration.cpp, plugin-volume/pulseaudioengine.cpp, plugin-worldclock/lxqtworldclock.cpp, plugin-worldclock/lxqtworldclockconfiguration.cpp, plugin-worldclock/lxqtworldclockconfigurationtimezones.cpp
Replaced by the ranged-based for loop.
Qt 5.7.1 is required. We use qAsConst().
The replacement brings some performance improvements. Container detachments
and container anti-pattern use were fixed.
=> Drop Qt foreach

plugin-taskbar/lxqttaskbutton.cpp, plugin-taskbar/lxqttaskbutton.h
Fixes https://github.com/lxde/lxqt/issues/1434.
NOTE: Since different window managers may show different behaviors in the case of maximized and fullscreen states, movement/resizing is disabled with those states.
=> Move and Resize items in task-button context menu

plugin-taskbar/lxqttaskbar.cpp
Fixes https://github.com/lxde/lxqt/issues/1303.
Detailed explanation:
When a window shows up, the signal `KWindowSystem::stackingOrderChanged` is emitted *before* `KWindowSystem::windowAdded`. The former signal is connected to the function `LXQtTaskBar::refreshTaskList()`, which calls the functions `LXQtTaskBar::addWindow()` and `LXQtTaskBar::removeWindow()` to add and remove monitored windows.
Connecting `LXQtTaskBar::refreshTaskList()` to the signal `KWindowSystem::stackingOrderChanged` not only is redundant but also causes a problem:
(1) It's redundant because the job of adding *new* windows should be done by `LXQtTaskBar::onWindowAdded()` connected to the signal `KWindowSystem::windowAdded`. However, with the current code, `LXQtTaskBar::addWindow()` is never called by that function …
=> Set the initial task button text (and icon) correctly

plugin-mainmenu/xdgcachedmenu.cpp
..as there is no need to use the XdgIcon version (and there are
problems with caching in the XdgIcon::fromTheme).
ref. lxde/lxqt#1444
=> mainmenu: Use the QIcon::fromTheme()

plugin-mainmenu/xdgcachedmenu.cpp
..overload, because it fails for absolute file names with vector
graphics (.svg etc.).
fixes lxde/lxqt#1451
=> mainmenu: Don't use "fallback" QIcon::fromTheme

plugin-kbindicator/src/kbdstateconfig.cpp
Previously the 'Configure layouts' button opened the config-input dialog in
the default (Mouse) page.
Now it opens in the 'Keyboard Layout' page. That's more user friendly.
=> plugin-kbindicator: Go directly to the Keyboard Layout config page

plugin-taskbar/lxqttaskbar.cpp, plugin-taskbar/lxqttaskgroup.cpp
Fixes https://github.com/lxqt/lxqt/issues/1482
If a task button is removed because of a class change and its window is still acceptable, it should be added under a new group.
=> Fix task button removal on class change

plugin-mainmenu/lxqtmainmenuconfiguration.cpp
5.11 Qt headers do not indirectly include QAction resulting in compile
time errors like:
| lxqtmainmenuconfiguration.cpp:71:105: error: no matching function for call to 'LXQtMainMenuConfiguration::connect(QAction*, const char [13], LXQtMainMenuConfiguration*, const char [17])'
Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>
=> Qt 5.11 beta: lxqtmainmenuconfiguration.cpp: include QAction explicitely

panel/config/configpaneldialog.cpp, panel/config/configpaneldialog.h, panel/config/configpanelwidget.cpp, panel/config/configpanelwidget.h, panel/config/configpanelwidget.ui, panel/lxqtpanel.cpp, panel/lxqtpanel.h, panel/lxqtpanelapplication.cpp, panel/lxqtpanelapplication.h
Closes https://github.com/lxqt/lxqt/issues/470
When a light widget style is used with a dark panel, the symbolic SVG icons follow the style and become dark on the panel. The right way of solving such issues is assigning a dark widget style to the panel but neither Fusion nor Breeze can do that.
This patch is about the "wrong way". It gives a separate icon set to the panel with unavoidable side effects but is optional and may be used as the last resort.
=> Optional overriding of icon theme for panels

plugin-spacer/spacer.h
It is always used as a boolen and assigned boolean values, so change the
type from int to bool.
=> spacer: Change type of mExpandable

plugin-mount/actions/deviceaction.cpp, plugin-mount/actions/deviceaction.h, plugin-mount/actions/deviceaction_info.cpp
As at the time of removal we don't get the device description from
solid(kf5).
fixes lxqt/lxqt#1646
=> mount: Store device names to show them upon remove

plugin-colorpicker/colorpicker.cpp
If the widget has contents margins and the panel has a border and/or a padding added, then the color picker layout breaks. In addition, keep the spacing between the QPushButton and the QLineEdit to the minimum.
Before removing the contents margins:
After removing the contents margins:
I don't know if the `setFixedXXX` lines in `ColorPicker::realign()` are really necessary. The height is fine with all of them commented.
=> Remove contents margins and reduce spacing

panel/config/configpanelwidget.cpp, panel/config/configpanelwidget.h, panel/config/configpanelwidget.ui, panel/lxqtpanel.cpp, panel/lxqtpanel.h
Closes https://github.com/lxqt/lxqt-panel/issues/930
The default is the previous behavior, namely, the 4-px margin of a hidden panel is visible. If the option is toggled, the margin will still exist but invisibly.
NOTE: `realign()` doesn't seem needed inside `LXQtPanel::setVisibleMargin` but is harmless.
A screenshot of the new config:
=> An option for invisibility of hidden panel margin

plugin-directorymenu/directorymenu.cpp, plugin-directorymenu/directorymenu.h, plugin-directorymenu/directorymenuconfiguration.cpp, plugin-directorymenu/directorymenuconfiguration.h, plugin-directorymenu/directorymenuconfiguration.ui
In issue lxqt/lxqt#1557, I proposed adding a feature to the directory menu plugin that would allow the user to open a selected terminal. I already have almost all of the code written, so I figured I would submit it. So far, it supports QTerminal and Konsole. I plan on adding support for xterm as well.
=> directory menu: Open in terminal

plugin-worldclock/lxqtworldclock.cpp, plugin-worldclock/lxqtworldclock.h, plugin-worldclock/lxqtworldclockconfiguration.cpp, plugin-worldclock/lxqtworldclockconfiguration.ui
Adds the option to not show the week number in the calendar widget.
Implements https://github.com/lxqt/lxqt/issues/1620
=> plugin-worldclock: Makes showing the week number optional

CMakeLists.txt
Stop using LXQT_MINIMUM_VERSION as the minimum required version for
lxqt-globalkeys.
lxqt-globalkeys is a lxqt-globalkeys-ui dependency.
Closes #1022.
=> cmake: Enhance lxqt-globalkeys minimum required version

plugin-statusnotifier/statusnotifierbutton.cpp, plugin-statusnotifier/statusnotifierbutton.h
Fixes https://github.com/lxqt/lxqt-panel/issues/1061
Rarely, some apps may change paths of their tray icons (bad codes?). Other DEs support that.
=> Get icon path before fetching icon in Status Notifier

plugin-tray/CMakeLists.txt, plugin-tray/lxqttray.cpp, plugin-tray/lxqttray.h, plugin-tray/lxqttrayconfiguration.cpp, plugin-tray/lxqttrayconfiguration.h, plugin-tray/lxqttrayconfiguration.ui, plugin-tray/lxqttrayplugin.h, plugin-tray/trayicon.cpp, plugin-tray/trayicon.h
It's mildly annoying that system tray icons show up in a different order each time LXQt is started.  Alphabetical order isn't always ideal, but at least it's consistent.  Potentially, in future, we could make the icon order customizable by the user.
=> Show system tray icons in a predictable order

plugin-taskbar/lxqttaskbutton.cpp, plugin-taskbar/lxqttaskbutton.h
Window icons typically come in several sizes, and KWindowSystem::icon() allows us to provide a size hint to get an icon close to the size we want to display.  Providing this hint makes the icons displayed in the taskbar clearer, since for common sizes (16x16, 24x24, etc.) they won't need to be scaled.
=> Fetch window icons in an appropriate size to avoid scaling

plugin-statusnotifier/CMakeLists.txt, plugin-statusnotifier/statusnotifierwidget.cpp
Do all the initial DBus logic in separate thread to avoid blocking the
main UI thread.
ref. #1064
=> statusnotifier: Don't (possibly) block on init

plugin-mainmenu/lxqtmainmenu.cpp, plugin-mainmenu/menustyle.cpp, plugin-mainmenu/menustyle.h
If we're using the default font size from the desktop theme, we
should use the default icon size as well.  Otherwise we'll frequently
end up with a size that requires re-scaling icons, causing them to
appear blurry.
=> Only override the menu icon size if a custom font size is selected.

plugin-mainmenu/lxqtmainmenu.h, plugin-statusnotifier/statusnotifier.h, plugin-taskbar/lxqttaskbarplugin.h
follow up for lxqt/lxqt-panel/pull/1074
plugin-mainmenu: Avoid char raw strings literals memory allocations
plugin-statusnotifier: Avoid char raw strings literals memory allocations
plugin-taskbar: Avoid char raw strings literals memory allocations
Please add anything i missed - at least it build again.
=> WIP: Follow up for Strings

plugin-statusnotifier/sniasync.h, plugin-statusnotifier/statusnotifierwatcher.cpp, plugin-statusnotifier/statusnotifierwidget.cpp
In case there is another "server" serving the SNI, allow queuing our
registration to overtake SNI serving after the existing one shuts down:
- allow waiting for org.kde.StatusNotifierWatcher registration
- do better logging
=>  statusnotifier: Enhance service name registration

.travis.yml
Since Qt 5.12.3 [1], Qt binaries can run on old kernels even if it's
compiled with statx support.
This eliminates the need to maintain another qt package, and it is also a preparation step for the upcoming Qt 5.13 update in Arch Linux.
[1] https://github.com/qt/qtbase/commit/7148dfc67ff20c1c625d203aa47b574b3aaa5db1
=> Use vanilla Qt instead of patched one

plugin-taskbar/lxqttaskbutton.cpp
lxqt-panel is still far from usable under kwin_wayland. At least it doesn't crash often now.
Ref: https://github.com/lxqt/lxqt/issues/10
=> Fix a crash under kwin_wayland

plugin-taskbar/lxqttaskgroup.cpp, plugin-taskbar/lxqttaskgroup.h
And do nothing with its corresponding windows.
IMHO, the left click behavior of the task manager is counter-intuitive when there is a group of two or more buttons because the user cannot predict what will happen to which window of the same app on clicking its single task button (unless he remembers the order of appearance of its windows).
This patch prevents confusion by showing the group popup in such cases, so that the user could choose what to do with each window. That's similar to the behavior of KDE Plasma's task manager too.
Closes https://github.com/lxqt/lxqt/issues/1725
=> Only show group popup on left clicking a grouping task button

panel/lxqtpanelapplication.cpp
Be careful with this. This is some kind of workaround I do not understand *at all*. But passing a deleted object into a function is also no good.
=>  lxqtpanelapplication: do not use deleted variable

plugin-taskbar/lxqttaskbar.cpp, plugin-taskbar/lxqttaskbar.h, plugin-taskbar/lxqttaskbarconfiguration.cpp, plugin-taskbar/lxqttaskbarconfiguration.ui, plugin-taskbar/lxqttaskbutton.cpp, plugin-taskbar/lxqttaskbutton.h
This is related to wishlist issue https://github.com/lxqt/lxqt/issues/1496
I added support for using the mouse wheel to raise/minimize windows on the taskbar.  I made a modification to the "Configure Task Manager" settings screen, where I removed the "cycle through windows" checkbox and replaced it with a "Mouse Wheel" section that has a dropdown that lets the user choose disabled, cycle through (so this option is still there), or the raise/minimize behavior.
I added a configurable threshold value in this section.  My mouse wheel had an 80-90% success rate, but sometimes the "scroll amount" value from my wheel was too small (200px, maybe?) and the wheel event didn't register.  I set it to 0 personally, but I kept the default at the previous value of 300.
_I also attached a small fix for …
=> Taskbar wheel event additions

plugin-taskbar/lxqttaskbutton.cpp, plugin-taskbar/lxqttaskbutton.h
Since Qt 5.12, tool button texts are middle-elided. This patch restores right eliding by using a simpler and better way of painting and using the button as the paint device.
Closes https://github.com/lxqt/lxqt-panel/issues/1162
=> Better text eliding and painting of task buttons

plugin-mainmenu/lxqtmainmenu.cpp, plugin-mainmenu/lxqtmainmenu.h
While the user is typing in the search field, LXQt Panel does lots of computations (searching for the string that's typed at the moment in lots of desktop entries and updating the menu by considering the found matches), which can result in input blocking and GUI freeze, especially with fast typing. To test that, you could keep the key "A" pressed in the search filed if you have an enough number of menu items in you main menu.
This patch starts searching (filtering) only when the user stops typing. The average typing speed is 200 characters per minute. Here, an interval of 350 ms is used for a smoother filtering.
=> Smoother menu search

plugin-volume/lxqtvolume.cpp, plugin-volume/lxqtvolume.h, plugin-volume/lxqtvolumeconfiguration.cpp, plugin-volume/lxqtvolumeconfiguration.h, plugin-volume/lxqtvolumeconfiguration.ui
If "Always notify about…" is checked, the new box "Notify about volume changes with keyboard" will be disabled and checked. If the user unchecks the former, the latter will be enabled. Finally, if the user unchecks the second box, all notifications will be disabled.
The change is backward-compatible because the default value of the new key is "true".
Closes https://github.com/lxqt/lxqt-panel/issues/1171
=> Added an option to toggle volume notifications with keyboard

panel/ilxqtpanel.h, panel/lxqtpanel.h, plugin-quicklaunch/lxqtquicklaunch.cpp, plugin-quicklaunch/quicklaunchbutton.cpp
DND is also considerd (dropping of main menu items and moving icons while pressing `Ctrl`).
Closes https://github.com/lxqt/lxqt/issues/1746
=> Made quicklaunch respect Panel's lock state.

plugin-taskbar/lxqttaskbar.cpp, plugin-taskbar/lxqttaskbarconfiguration.cpp, plugin-taskbar/lxqttaskbutton.cpp
(1) The obsolete method `QWheelEvent::delta` is replaced.
(2) The signal-slot connection syntax is updated (only in a relevant source file).
(3) The signal `QSpinBox::valueChanged` is replaced by `QAbstractSpinBox::editingFinished` to prevent redundant writes (that should be done in all similar places, IMHO).
NOTE: This is a fix for https://github.com/lxqt/lxqt-panel/pull/1161
=> Cleanup and fixes for taksbar code

panel/lxqtpanel.cpp
Since Qt 5.13, positioned backgrounds of plugins (so-called "handles") aren't updated on changing panel position. This should be a new Qt bug. As a workaround, the stylesheet is reset before being updated.
Closes https://github.com/lxqt/lxqt-panel/issues/1164
=> Qt Workaround: Reset panel style sheet before updating it

plugin-quicklaunch/quicklaunchbutton.cpp, plugin-quicklaunch/quicklaunchbutton.h
It's unnecessary because we already have the right-click context
menu which provides the same options (and then some).
This fixes the issue of the launcher buttons being too wide (#1223)
because Qt no longer allocates space for the little arrow that
indicates the presence of a popup menu.  (The arrow was previously
hidden by overriding paintEvent(), but space was still allocated.)
=> quicklaunch: Remove press-and-hold popup menu from launchers.

panel/lxqtpanel.cpp
…Instead of checking if its rectangle contains the cursor.
Fixes https://github.com/lxqt/lxqt-panel/issues/1266
=> Check if panel is under mouse on auto-hiding

panel/config/configpanelwidget.cpp, panel/lxqtpanel.cpp
Qt → `src/widgets/kernel/qdesktopwidget.cpp` was consulted.
NOTE: Although the patch passed my tests with two monitors (by changing their alignment and resolutions and also repositioning the panel), it needs more tests.
=> Removed QDesktopWidget from panel

plugin-kbindicator/src/content.cpp, plugin-kbindicator/src/content.h, plugin-kbindicator/src/kbdstateconfig.cpp, plugin-kbindicator/src/kbdstateconfig.ui, plugin-kbindicator/src/kbdwatcher.cpp, plugin-kbindicator/src/settings.cpp, plugin-kbindicator/src/settings.h
ref. lxqt/lxqt#1162
This is some kind of basic support for displaying country flags instead of letters. We don't provide any flag images by our self, instead the user can set a pattern for constructing the path for flag. In case of empty/wrong configuration or file with flag does not exist (or is not an image easily shown by `QIcon`) the indicator falls back to the letter country code.
I tested it with the debian's [iso-flags-svg](https://tracker.debian.org/pkg/iso-flags-svg).
Is something like that acceptable?
=> [WIP] kbindicator: Add basic support for country flags

plugin-mainmenu/lxqtmainmenu.cpp
This prevents the fade-out animation of the "clear" icon which
would occur when the menu was shown the next time after performing
a search.  IMHO, animations on newly-shown widgets are undesirable.
=> mainmenu: Clear search edit on hide, rather than on show.

plugin-desktopswitch/desktopswitch.cpp
Due to a change in KWindowSystem or X11 or…, changing the desktop layout inside `DesktopSwitch::realign()` may call `LXQtPanel::realign`, which calls `DesktopSwitch::realign()` and so, creates an infinite loop. But, actually, the desktop layout needs to be set only when the setting is changed.
The patch is backward compatible.
Fixes https://github.com/lxqt/lxqt-panel/issues/1352
=> Fixed high CPU usage of Desktop Switch

plugin-taskbar/lxqttaskbarconfiguration.cpp, plugin-taskbar/lxqttaskbutton.cpp, plugin-taskbar/lxqttaskbutton.h, plugin-taskbar/lxqttaskgroup.cpp, plugin-taskbar/lxqttaskgroup.h
This patch adds two options to move window to next/previous desktop by scrolling up/down and conversely. It also corrects two flaws:
1. It considers two mouse wheel rotations separate from each other if there is a minimum interval of 250ms between them. Without this, delta threshold won't make sense because delta could have increased 2 minutes ago, for example. Moreover, wheel movement will be impractical without it.
2. It shows the group popup for grouped buttons on wheel rotation, instead of applying the wheel event (to raise, minimize, move…). The reason is that, otherwise, the user couldn't predict what will happen to which window inside the group.
Closes https://github.com/lxqt/lxqt-panel/issues/1356
=> Task button: Option to move window with mouse wheel

plugin-backlight/backlight.cpp, plugin-backlight/resources/backlight.desktop.in
And not a gnome-specific icon.
=> Use our own brightness icon for the new backlight plugin

panel/lxqtpanel.cpp
This patch allows the panel to be positioned at virtual screen edges and not only at the farthest edges, provided that no part of it can be between 2 screens.
Closes https://github.com/lxqt/lxqt/issues/1787
=> Let panel be at virtual screen edges but not between screens

plugin-sensors/lxqtsensors.cpp, plugin-sensors/lxqtsensors.h
Only a style sheet guarantees that custom colors are applied because not all widget styles use palettes to draw progress bars.
Closes https://github.com/lxqt/lxqt/issues/1810
Explanation:
As Qt doc says (see https://doc.qt.io/qt-5/qwidget.html#palette-prop): "The current style, which is used to render the content of all standard Qt widgets, is free to choose colors and brushes from the widget palette, or in some cases, to ignore the palette (partially, or completely)…"
Therefore, in general, it's a bad practice to use palettes in a code to customize widgets. The correct method is either using Qt style sheets (the easy way) or drawing the customized widgets completely by using `QStyle` (cumbersome).
=> Use a stylesheet for progress-bars of Sensors plugin

plugin-statusnotifier/CMakeLists.txt, plugin-statusnotifier/statusnotifier.h, plugin-statusnotifier/statusnotifierbutton.cpp, plugin-statusnotifier/statusnotifierbutton.h, plugin-statusnotifier/statusnotifierconfiguration.cpp, plugin-statusnotifier/statusnotifierconfiguration.h, plugin-statusnotifier/statusnotifierconfiguration.ui, plugin-statusnotifier/statusnotifierwidget.cpp, plugin-statusnotifier/statusnotifierwidget.h
The items can be auto-hidden or always shown/hidden. The default is "Always show".
If there are (auto-)hidden items, an extra button will appear, which shows all items when clicked; then (auto-)hidden items will be made hidden again after 2 seconds if the the mouse cursor leaves Status Notifier.
The auto-hidden items that need attention are shown for 5 minutes (the interval is configurable). Apart from explicit attention requests, an icon change is also interpreted as an attention request with auto-hiding. That's useful, for example, when a battery or WiFi icon changes.
Closes https://github.com/lxqt/lxqt/issues/1012
=> Implemented auto-hiding for Status Notifier

plugin-tray/trayicon.cpp
This workaround causes https://github.com/lxqt/lxqt/issues/1817.
I myself cannot reproduce https://github.com/lxqt/lxqt/issues/945 after this change, so to me it seems safe to remove this workaround.
@renegat since you reported that issue a few years back and in case you're still around and reading this: can you confirm that https://github.com/lxqt/lxqt/issues/945 is no longer happening even with this workaround removed?
In any case, I'm creating this pull request for you to discuss, if you rather want to keep having https://github.com/lxqt/lxqt/issues/1817 or take the risk of reintroducing https://github.com/lxqt/lxqt/issues/945.
=> Remove delayed initialization of tray icons.

plugin-taskbar/lxqttaskbutton.cpp, plugin-taskbar/lxqttaskbutton.h
Implemented this option which i find very useful in other DEs, since my second screen is a TV and it's not always on, i'm a noob in c++, so let me know if something needs fixing... Also since i was digging through kwindowsystem and qt docs for this, i can try to remove QDesktopWidget later since it is being deprecated.
=> Task Button: Add option to move to next monitor

plugin-taskbar/lxqttaskbar.cpp, plugin-taskbar/lxqttaskbar.h, plugin-taskbar/lxqttaskbarconfiguration.cpp, plugin-taskbar/lxqttaskbarconfiguration.ui
This option places new windows right after existing windows of the same class, when ungrouped. I think it's a very useful feature for those who use ungrouped windows.
instead of for example:
`terminal | pcman | firefox | pcman | terminal`
if reorders as:
`terminal | terminal | pcman | pcman | firefox`
and next terminal is placed between terminal and pcman, it just moves the new window to the right of last window of the same class.
Not sure about the config ui, couldn't come up with a better description and placement for the checkbox.
The code could be improved, maybe adding class name to `LXQtTaskGroup` for easier searching.
=> Taskbar: Add option to place new windows next to existing windows of same class when ungrouped

plugin-worldclock/lxqtworldclockconfigurationmanualformat.ui
First, milliseconds have no place in World Clock. Second, if they did, "trailing" should replace "leading" in their explanation.
Closes https://github.com/lxqt/lxqt-panel/issues/1439
=> World Clock: Removed incorrect and redundant explanation of milliseconds

plugin-desktopswitch/desktopswitch.cpp
Just make the container const.
=> Prevent possible C++11 range loop container detachment

plugin-worldclock/lxqtworldclock.cpp
When searching for a lowercase in case sensitive mode, there's no need to
convert the string to lowercase.
A QLatin1Char() is enough here.
=> Remove not needed allocation

panel/plugin.cpp
Plugins whose widgets are (tool) buttons need both a geometry update and a size adjustment when they are shown; otherwise, their style sizes will be used and their alignments will be incorrect. Doing so for all plugins guarantees correct sizes everywhere.
Fixes https://github.com/lxqt/lxqt-panel/issues/1425
=> Fixed the sizes and alignments of some plugins at startup

plugin-mainmenu/lxqtmainmenu.cpp, plugin-mainmenu/lxqtmainmenu.h
Each right-click menu has two items for adding to desktop and copying to clipboard.
Closes https://github.com/lxqt/lxqt/issues/383
=> Added right-click menu to main menu items

plugin-mount/CMakeLists.txt, plugin-mount/actions/ejectaction.cpp, plugin-mount/actions/ejectaction.h, plugin-mount/actions/ejectaction_nothing.cpp, plugin-mount/actions/ejectaction_nothing.h, plugin-mount/actions/ejectaction_optical.cpp, plugin-mount/actions/ejectaction_optical.h, plugin-mount/configuration.cpp, plugin-mount/configuration.ui, plugin-mount/lxqtmountplugin.cpp, plugin-mount/lxqtmountplugin.h
On some laptops optical drives with slot loading come with a dedicated eject button. This patch allows one to configure the mount plugin to respond to it by ejecting the disk.
Add XF86Eject button action:
* register a global key shortcut
* allow one to choose between no action and optical disk ejection
* notify after disk ejection
=> Support optical drives with slot loading and a dedicated eject button

plugin-mainmenu/lxqtmainmenu.cpp
Compilation with menu-cache was made impossible by a recent commit.
=> Allow compilation with menu-cache again

plugin-statusnotifier/statusnotifier.h
It helps in maintenance and the compiler stops issuing warnings.
=> Add missing override specifiers

panel/lxqtpanel.cpp, panel/lxqtpanel.h
fix for #1483
at first i wanted to emit a signal from panel to let the menu recalculate its position, but thought this one would be better since it's a more generic fix (although i don't know if there's another popup u can open with key shortcut)
=> fix for menu overlap

plugin-taskbar/lxqttaskbutton.cpp
The use of nullptr is deprecated.
=> Use explicit QFlags default constructor instead of nullptr

plugin-taskbar/lxqttaskbar.cpp
The use of an empty QStringLiteral() causes unneeded code bloat.
=> Use empty QLatin1String

plugin-worldclock/lxqtworldclock.cpp
Using of liblxqt's `RotatedWidget::setTransferWheelEvent()` caused the mouse wheel event to be sent twice to the clock's label and interfere with the correct changing of the time zone. The label already received the wheel event and the above-mentioned method doubled it.
Fixes https://github.com/lxqt/lxqt-panel/issues/1512
=> Fixed changing of world clock's time zone with mouse wheel

panel/config/configpanelwidget.cpp, panel/config/configpanelwidget.h, panel/config/configpanelwidget.ui, panel/lxqtpanel.cpp, panel/lxqtpanel.h
With the new option checked (it's not checked by default), an auto-hiding panel gets hidden when it overlaps a window and is shown when there's no overlap.
Closes https://github.com/lxqt/lxqt-panel/issues/1515
=> Optionally auto-hide panel only when it overlaps a window

plugin-colorpicker/translations/colorpicker.ts, plugin-colorpicker/translations/colorpicker_arn.ts, plugin-colorpicker/translations/colorpicker_ast.ts, plugin-colorpicker/translations/colorpicker_ca.ts, plugin-colorpicker/translations/colorpicker_cs.ts, plugin-colorpicker/translations/colorpicker_cy.ts, plugin-colorpicker/translations/colorpicker_da.ts, plugin-colorpicker/translations/colorpicker_de.ts, plugin-colorpicker/translations/colorpicker_gl.ts, plugin-colorpicker/translations/colorpicker_hu.ts, plugin-colorpicker/translations/colorpicker_it.ts, plugin-colorpicker/translations/colorpicker_ja.ts, plugin-colorpicker/translations/colorpicker_nb_NO.ts, plugin-colorpicker/translations/colorpicker_nl.ts, plugin-colorpicker/translations/colorpicker_pl.ts, plugin-colorpicker/translations/colorpicker_pt_BR.ts, plugin-colorpicker/translations/colorpicker_ru.ts, plugin-colorpicker/translations/colorpicker_sk_SK.ts, plugin-colorpicker/translations/colorpicker_sv.ts, plugin-colorpicker/translations/colorpicker_tr.ts
No idea where those come from originally, I imported them time ago in weblate without realizing that there are 0 words, colorpicker has no settings.
=> remove empty translations

CHANGELOG, plugin-taskbar/lxqttaskgroup.cpp
The lack of checking didn't have an effect with the official Qt releases but it causes a bug with the latest official patches. Logically, the pressed mouse buttons should have always been checked.
Closes https://github.com/lxqt/lxqt-panel/issues/1600
=> Check pressed mouse buttons before closing grouped task popup

plugin-mainmenu/actionview.cpp, plugin-mainmenu/actionview.h, plugin-mainmenu/lxqtmainmenu.cpp
To make search results behave the same as regular menu actions. 
- Added drag and drop to search results
- Added context menu to search results
plus a small change:
- Changed variable name `QString action` to `actionString` to avoid conflict with `QAction *action` declared earlier.
=> plugin-mainmenu - add contextmenu and drag/drop to search results

plugin-desktopswitch/desktopswitch.cpp
If only the active button is shown, the layout of desktop switcher might grow and shrink on switching desktop because, in a very short interval, the number of visible buttons will change. That may cause a flickering under rare and random circumstances. When it happens, it can be quite visible because it may shake nearby plugins.
The flickering is prevented here by disabling the layout before changing visibilities of buttons and re-enabling it afterward.
=> Prevent flickering of desktop switcher when only active button is shown

plugin-customcommand/lxqtcustomcommand.cpp
maybe fixes #1710 ?
i also noticed without this commit there's a warning `QProcess: Destroyed while process ("bash") is still running.`
=> CustomCommand: close QProcess on destructor

plugin-taskbar/lxqttaskbutton.cpp
issue #1665 
now shows desktop names in format "[number]: [name]" instead of generic "Desktop [number]"
also fixed shortcut(?) key for "Move to Next Monitor" as "N" conflicts with "Minimize"
=> Show desktop names on taskbutton's context menu

plugin-sysstat/lxqtsysstat.cpp
Note: Don't even shrink the history on decreasing widget width.
Fixes #1614
=> sysstat: Keep stat history on width change

plugin-mainmenu/lxqtmainmenu.cpp, plugin-mainmenu/lxqtmainmenu.h
In acc90ef308a4e15a0ab72cb7a7403e41a9988b36 (#255) closing the menu on
any "modifier" press. This workaround was clashing with the expected
behavior in search QLineEdit (#1717).
This commit reintroduces closing the menu just upon releasing the defined
menu shortcut and tries to solve also specific shortcuts (when the
shortcut itself consists only from modifiers).
closes #1717
=> mainmenu: Close menu only on shortcut press

plugin-tray/sniproxy.cpp, plugin-tray/sniproxy.h
- increase the client (painting) window to 128x128
- detect opaque area (some apps don't honor the size of the window and
paint small icons in the middle) and use just that for icon image
- present icon images up to 128x128 to SNI (if needed the image is
scaled up for multiple resolutions)
fixes #1735
=> tray: Support bigger icon sizes

plugin-statusnotifier/statusnotifierconfiguration.cpp, plugin-statusnotifier/statusnotifierconfiguration.h
Here the main change is about resetting all visibility states when the Reset button is clicked.
Related to https://github.com/lxqt/lxqt-panel/issues/1741
=> Fixed Reset button in Status Notifier config dialog

panel/lxqtpanelpluginconfigdialog.cpp, panel/lxqtpanelpluginconfigdialog.h, panel/plugin.cpp, panel/pluginsettings.cpp, panel/pluginsettings.h, plugin-taskbar/lxqttaskbar.cpp
- Add emitting settingsChanged() into PluginSettings::loadFromCache() to
notify plugin/users, that settings were updated. Previously the signal
was probably emitted by the underlying object detecting the settings
file changed, but this is not the case any more (probably enhancement
in the underlying Qt's QSettings optimization).
- Add PlutingSettings::storeToCache() for the plugin configure dialog to
be able to store to cache on closing the dialog -> after re-showing or
showing freshly created one, we expect to be able to reset to the
values shown initialy in this dialog.
- Delete plugin's config dialog before deleting the plugin object
itself, as the config dialog can rely/use other plugin objects and
deleting/closing the dialog late after plugin object destroyed can
cause problems …
=> panel/plugin: Fix settings storing/restoring

plugin-worldclock/lxqtworldclock.cpp
This will honor the all the LANG & LC_* vars.
Fixes #1489
=> worldclock: Use system locale

plugin-quicklaunch/quicklaunchaction.cpp, plugin-quicklaunch/quicklaunchaction.h, plugin-quicklaunch/quicklaunchbutton.cpp, plugin-quicklaunch/quicklaunchbutton.h
The reloading happens if the (edited) desktop entry is valid/applicable; otherwise, the previous data will be remembered and used.
Closes https://github.com/lxqt/lxqt-panel/issues/1795
=> Added context items to Quick Launch for reloading desktop entries

plugin-volume/volumepopup.cpp
It may make a difference under Wayland, with no change under X11.
Closes https://github.com/lxqt/lxqt-panel/issues/1815
=> Set window flags of volume popup explicitly

plugin-quicklaunch/quicklaunchaction.cpp
The code checks the keys "desktop", "file" and "name/exec/icon" in this order and ignores the rest if one is found. Because of that, for example, if the user config file contains "name/exec/icon" but another config file contains "desktop" *for the same Quick Launch button*, the former will be ignored and the latter will be used instead.
To fix this problem, the patch sets "desktop" and "file" to empty strings for executable scripts. It also sets "desktop" to an empty string for files.
If the user has encountered the bug before this patch, he should either remake his script/file launcher(s) or temporarily change some setting to get rid of the problem.
Fixes https://github.com/lxqt/lxqt-panel/issues/1822
=> Fixed Quick Launch with multiple config files

plugin-volume/lxqtvolume.cpp, plugin-volume/lxqtvolumeconfiguration.cpp, plugin-volume/lxqtvolumeconfiguration.h, plugin-volume/lxqtvolumeconfiguration.ui, plugin-volume/volumebutton.cpp, plugin-volume/volumebutton.h
The code shouldn't try to show or hide the popup based on the enter and leave events of its button because those events aren't (or shouldn't be) emitted when the popup is visible.
Also, the option for showing the popup on button mouseover has been removed, because the popup couldn't be hidden when the cursor left the button.
Previously, the code made use of a Qt issue to do the above-mentioned actions, but the issue was avoided for another purpose in V1.2.0.
Fixes https://github.com/lxqt/lxqt-panel/issues/1839
=> Fixed a regression in volume popup

panel/lxqtpanel.cpp
Since xfwm4 4.18 [1], windows with `_NET_WM_STATE_ABOVE` cover fullscreen windows. Qt's XCB plugin sets `_NET_WM_STATE_ABOVE` for windows with the flag `Qt::WindowStaysOnTopHint` [2], so panels cover fullscreen windows.
On the other hand, panels have the window type dock [3], which still covers normal windows per the spec [4] and in xfwm4.
The xfwm4 change [1] mentions it follows GNOME, so the issue may be present on Mutter as well.
[1] https://gitlab.xfce.org/xfce/xfwm4/-/commit/cdcce73653d430d9cbddba3873e4e98ddae0a6a8
[2] https://github.com/qt/qtbase/blob/v5.15.7-lts-lgpl/src/plugins/platforms/xcb/qxcbwindow.cpp#L1060
[3] https://github.com/lxqt/lxqt-panel/blob/dbd15d48e0cd8a0b92c769fb9ca875f94154ad74/panel/lxqtpanel.cpp#L167
[4] …
=> panel: avoid covering fullscreen windows

plugin-volume/volumebutton.cpp, plugin-volume/volumebutton.h
They were useless under X11, but the existence of `ILXQtPanel` inside `VolumeButton` made the volume popup have an incorrect position under Wayland.
Closes https://github.com/lxqt/lxqt-panel/issues/1815
=> Removed redundant classes from `VolumeButton` in volume plugin

plugin-dom/treewindow.cpp
Fix missing change to a commit that corrected typos in identifiers. (#1867) Someone reported a failed build due to this.
=> Missed a typo causing failed build

plugin-quicklaunch/lxqtquicklaunch.cpp
Eliminates error message "QLayout::removeWidget: Cannot remove a null widget." when starting with a populated quicklaunch, or when adding members.
=> Nullity check for quicklaunch placeholder widget

plugin-worldclock/lxqtworldclock.cpp
Found the problem only after comparing the seconds shown by Panel's clock with the seconds hand of a Qt analog clock I'd made.
Fixes https://github.com/lxqt/lxqt-panel/issues/1880
=> Fixed the seconds shown by clock

plugin-worldclock/lxqtworldclock.cpp
The mistake didn't have a serious consequence.
Fixes https://github.com/lxqt/lxqt-panel/issues/1882
=> Fixed a mistake in World-Clock's code when seconds are shown

plugin-taskbar/lxqttaskbutton.cpp, plugin-taskbar/lxqttaskgroup.cpp
We need to test the real urgency hint, not just the flag about urgency hint changed.
In the previous commit 44c46c163b7282fd521b3cf361e6f87c88a48a9f, bug for clearing of the urgency widget hint was introduced also.
I was too hurry in the previous PR #1901, it was working just by a chance and resetting the urgency style was buggy also. This should fix both shortcomings.
=> taskbar: Fix checking/clearing of urgency

plugin-taskbar/lxqttaskbutton.cpp, plugin-taskbar/lxqttaskbutton.h
When focus stealing prevention exists, the only way of having a consistent window cycling with mouse wheel is forcing window activation. Since this is a taskbar, it is allowed to do so.
Fixes https://github.com/lxqt/lxqt-panel/issues/1904
=> Fixed window cycling with wheel and focus stealing prevention

plugin-volume/pulseaudioengine.cpp
1. The initial displayed volume (immediately after Panel's startup) is fixed when volumes beyond 100% are not allowed (the default).
2. The previous behavior is kept when volumes beyond 100% are allowed.
3. The displayed volume is updated when the option about volumes beyond 100% is toggled.
Fixes https://github.com/lxqt/lxqt-panel/issues/1928
=> Fixed the initial displayed volume with PulseAudio

plugin-volume/volumebutton.cpp, plugin-volume/volumepopup.cpp
… by setting their parent widgets. X11 sees no change.
Fixes https://github.com/lxqt/lxqt-panel/issues/1927
=> Fixed the tooltips of volume control under Wayland

.ci/build.sh
Most KF5 packages are renamed to have a suffix, and provides= is later droped.
See: https://gitlab.archlinux.org/archlinux/packaging/packages/solid5/-/commit/b04eb194f02b4340aa24aee6d8001b6306ea4ebd
See: https://gitlab.archlinux.org/archlinux/packaging/packages/lxqt-panel/-/commit/f25b78c90774196875308df034a3ab9ae7a7cc35
See: https://aur.archlinux.org/cgit/aur.git/commit/?h=lxqt-panel-git&id=f70ca49e16a5c3a074673462297ae4a58a014240
=> Rename kf5 packages

plugin-customcommand/lxqtcustomcommand.cpp, plugin-customcommand/lxqtcustomcommandconfiguration.cpp
This fixes crash when command is made of only whitespace characters. It's not detected as empty and upon argument split, it tries to access first element of an empty list.
Also trim when saving settings in `LXQtCustomCommandConfiguration` so placeholder text shows up on next run.
The crash happens for assert failure called from either `runCommand()` or `runDetached()`
`LXQtCustomCommandConfiguration` slots have `QString` passed by value, this could be optimized with pass by const  reference.
=> LXQtCustomCommand: trim command to remove spaces

plugin-fancymenu/lxqtfancymenuwindow.cpp, plugin-fancymenu/lxqtfancymenuwindow.h
* `CategoryView` and `AppView` can be styled independently.
* If you don't add a background for `CategoryView`, it'll have the background of `LXQtFancyMenuWindow` (previously it did only *without* stylesheets).
* The patch also enforces the stylesheet background color of `LXQtFancyMenuWindow` (if any) on widget styles that try to override it (like Kvantum).
=> Improved styling of views of Fancy Menu a little

plugin-fancymenu/lxqtfancymenuwindow.cpp
`QWidget::mapToGlobal` should have been used with the viewport, not with the view itself.
Also, set the window flag explicitly because, although there seems to be no problem under Wayland, we had seen a problem in another plugin when the flags weren't set explicitly.
=> Corrected context menu position of Fancy Menu

plugin-fancymenu/lxqtfancymenu.cpp, plugin-fancymenu/lxqtfancymenuconfiguration.cpp, plugin-fancymenu/lxqtfancymenuconfiguration.ui, plugin-fancymenu/lxqtfancymenuwindow.cpp, plugin-fancymenu/lxqtfancymenuwindow.h
The default is kept to be selection by clicking. The auto-selection delay can be set from 50 to 1000 ms, with its default being 250 ms (like in Qt menus).
Closes https://github.com/lxqt/lxqt-panel/issues/2000
=> Support auto-selection in Fancy Menu

plugin-fancymenu/lxqtfancymenucategoriesmodel.cpp, plugin-fancymenu/lxqtfancymenuwindow.cpp, plugin-fancymenu/lxqtfancymenuwindow.h
1. Tooltips of categories are removed because they were the same as displayed names and only disruptive.
2. The icon of config center button is corrected (its text was already corrected by @@stefonarch in https://github.com/lxqt/lxqt-panel/commit/ed50e7a9242509a298afffae77d4ed78547261b5).
3. About button is added.
=> Minor GUI cleanup for Fancy Menu

plugin-fancymenu/lxqtfancymenuappmap.cpp, plugin-fancymenu/lxqtfancymenuappmap.h, plugin-fancymenu/lxqtfancymenuappmodel.cpp, plugin-fancymenu/lxqtfancymenuappmodel.h, plugin-fancymenu/lxqtfancymenuwindow.cpp, plugin-fancymenu/lxqtfancymenuwindow.h
=> FancyMenu: support favorites reordening by drag drop

plugin-worldclock/lxqtworldclock.cpp
`QDateTime::toString` returned a localized string with Qt5, but it doesn't with Qt6.
=> Fixed localization of World Clock with Qt6

CMakeLists.txt, panel/CMakeLists.txt, panel/lxqtpanel.cpp, panel/lxqtpanel.h
=> Wayland Layer Shell

plugin-mount/menudiskitem.cpp, plugin-mount/menudiskitem.h, plugin-mount/popup.cpp
`Solid::StorageAccess::accessibilityChanged` isn't emitted when an encrypted volume is mounted by GLib/GIO (e.g., through pcmanfm-qt). This is a workaround.
Closes https://github.com/lxqt/lxqt-panel/issues/1639
=> Workaround for mount plugin with a GLib-mounted encrypted volume

plugin-customcommand/custombutton.cpp, plugin-customcommand/lxqtcustomcommand.cpp, plugin-customcommand/lxqtcustomcommand.h
Previously, only the vertical wheel scrolling worked, which might not be ideal with a touchpad.
A confession: My concern wasn't the touchpad ;) I made this patch as a workaround for a regression about Wayland, because of which, Qt's vertical and horizontal wheel events are swapped under special circumstances. However, the end result is independent of that regression.
=> Made horizontal wheel scrolling work with Custom Command

panel/lxqtpanel.cpp
… for bottom and right panels.
The problem was that some Wayland compositors returned global coordinates when anchors were applied, while some others (perhaps KWin) didn't. So, the patch uses local coordinates and changes them to the global ones in the end.
=> Fixed main popup positions under Wayland

plugin-backlight/backlight.cpp, plugin-colorpicker/colorpicker.cpp
Fixes an inconsistency in themes when they expect an expanding size policy, which is what most plugins have set. Some themes with incorrect styling due to this: KDE-Plasma, Ambiance, Kvantum.
=> Set size policy in plugin-backlight and plugin-colorpicker

panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp, panel/resources/panel.conf
Found by @stefonarch. Fixes https://github.com/lxqt/lxqt-panel/issues/2089
Also removed `preferred_backend` from the shipped config file to remain neutral.
=> Added a missing header

plugin-fancymenu/lxqtfancymenu.cpp, plugin-fancymenu/lxqtfancymenuconfiguration.cpp, plugin-taskbar/lxqttaskbar.cpp, plugin-taskbar/lxqttaskbarconfiguration.cpp
When adding a plugin in  a new panel default settings as in `panel.conf` are applied.
* Fancy Menu: search was not cleared 
* Taskbar: when adding a taskbar to a new empty panel with some windows open there was no space left to right click panel settings.
=> Default values for new widgets

plugin-directorymenu/directorymenu.cpp
Directory Menu's menu consists of:
- Open
- Open in terminal
- Directories [...]
Currently all icons were `folder`; this PR changes "Open" to `document-open` and "Open in terminal" to `utilities-terminal`. These icons are used in libfm-qt, for instance.
Screenshot (MATE icon theme):
=> Improve plugin-directorymenu icons (replace two generic icons)

panel/backends/wayland/wlroots/lxqttaskbarwlrwm.cpp, panel/backends/wayland/wlroots/lxqttaskbarwlrwm.h, panel/backends/wayland/wlroots/lxqtwmbackend_wlr.cpp, panel/backends/wayland/wlroots/lxqtwmbackend_wlr.h
This PR fixes the following problems:
* Multiple task buttons for a window and its child dialogs;
* Deactivation of task button on title change (e.g., because of a tab switch in pcmanfm-qt); and
* Deactivation of task button under other circumstances, like when dropdown QTerminal is shown.
It also fixes some logical issues in handling of parent changes, but I couldn't find a real world example for that.
Closes https://github.com/lxqt/lxqt-panel/issues/2097
=> Fixed issues in wlroots task buttons

panel/backends/lxqttaskbartypes.h, panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp, panel/backends/xcb/lxqtwmbackend_x11.cpp, plugin-taskbar/lxqttaskbutton.cpp
I have added two options, `MoveToLayer` and `MoveToOutput` options to `enum class LXQtTaskBarBackendAction` and made suitable changes to `plugin-taskbar/lxqttaskbutton.cpp`. Additionally, I have made changes to XCB and KWin plugins. On wlroots, the `Move to Layer` and `Move to Output` should be greyed out.
=> Optionally disable move-to-layer and move-to-output

panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp
Previously when a window was set to layer "KeepBelow" it could not be reset to "Normal" anymore.
=> LXQtWMBackend_KWinWayland: fix reset keep_below state

panel/backends/xcb/lxqtwmbackend_x11.cpp, plugin-desktopswitch/desktopswitch.cpp, plugin-desktopswitch/desktopswitch.h
This PR does three things:
1. It fixes the persistence of urgent hint in the switcher after closing a window with an urgent hint, and so, closes https://github.com/lxqt/lxqt-panel/issues/1917
2. When the property of a window changes, it checks the `Urgency` and `Workspace` properties of that window — in addition to `State` — and sets the switcher urgency accordingly.
3. It also corrects emitting of `windowPropertyChanged` with X11. Previously it was emitted with both `NET::WMDesktop` and `NET::WMGeometry` flags, while the second flag was redundant.
A word about 2:
When a window demands attention, its desktop does too. Also, when a window that demands attention is moved between desktops, the desktop that demands attention changes accordingly. These points weren't considered in the master …
=> Fixed the urgent hint of desktop switcher

plugin-directorymenu/directorymenu.cpp
This patch fixes two issues:
* The `Open in terminal` menu-item wouldn't work if no default terminal was defined. The patch minimizes the chance by choosing `xterm` in this case.
* The previous code worked only with QTerminal and Konsole, excluding all terminals that didn't have the `--workdir` option.
Closes https://github.com/lxqt/lxqt-panel/issues/2121
=> Fixed default terminal of directorymenu plugin

plugin-statusnotifier/statusnotifierconfiguration.cpp, plugin-statusnotifier/statusnotifierconfiguration.ui, plugin-statusnotifier/statusnotifierwidget.cpp
By default, the order is from the oldest to the newest item.
NOTE: This PR needs https://github.com/lxqt/liblxqt/pull/353
Closes https://github.com/lxqt/lxqt-panel/issues/2124
=> An option to reverse the order of tray items

plugin-colorpicker/translations/colorpicker.desktop.yaml, plugin-cpuload/translations/cpuload.desktop.yaml, plugin-desktopswitch/translations/desktopswitch.desktop.yaml
These were the only plugins whose titles were not capitalized in English.
"CPU monitor"
"Color picker"
"Desktop switcher"
=> Capitalize remaining plugin titles

plugin-worldclock/lxqtworldclock.cpp, plugin-worldclock/lxqtworldclock.h
The crash was in `deleteLater()`. The code is simplified, such that there's no need to `deleteLater()`. It's also good for X11.
Fixes https://github.com/lxqt/lxqt-panel/issues/2146
NOTE: This is similar to https://github.com/lxqt/lxqt-notificationd/pull/375 and https://github.com/lxqt/lximage-qt/pull/666, and shows that we should be more cautious when using `deleteLater()`.
=> Fixed a crash in worldclock popup on Wayland with Qt 6.8.0

panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp, panel/lxqtpanel.cpp
Unfortunately, several Wayland compositors won't let panel popups have focus if the panel does not accept focus.
However, some compositors don't have this issue, and we can use `KeyboardInteractivityNone` with them. The patch does that for `kwin_wayland`, 'wayfire' and 'hyprland', and with Qt ≥ 6.8 (because I'm not sure it works with previous versions of Qt).
NOTE: This is an ugly patch, but the current situation of Wayland compositors isn't better. The patch can be considered as a temporary solution.
=> Prevent panel from accepting focus with some Wayland compositors

panel/lxqtpanel.cpp
Since Qt 6.8.0, random artifacts are possible in a translucent panel — and, generally, in all translucent windows (based on QWidget, not QML) — under Wayland. They may happen when the panel starts. They're sometimes temporary, sometimes persistent, especially when the panel doesn't accept focus.
This is a simple workaround, which guarantees fully transparent pixels before painting.
NOTE: The workaround has been 100% effective for me elsewhere (also see https://github.com/lxqt/lxqt-notificationd/pull/402) and is effective in the case of panel too.
=> Workaround for translucency artifacts with Qt 6.8.0 on Wayland

plugin-mainmenu/lxqtmainmenu.cpp, plugin-mainmenu/lxqtmainmenu.h
Similar approach as in #2147, but we don't sacrifice the context menu triggered by "menu" key (if it is correctly triggered by Qt).
ref. #2145
=> mainmenu: Workaround lack of context menu with Qt 6.8.0

panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp, panel/lxqtpanel.cpp, panel/lxqtpanel.h
First, the method `LXQtWMBackend_KWinWayland::isAreaOverlapped()` needed enhancements.
Second, `QVariantAnimation` is used to set appropriate negative margins and have animation with auto-hiding. The animation is exactly like in X11.
NOTE: I'm not sure that negative margins work under other Wayland compositors, but for now, auto-hiding on overlapping can't work with them. KWin wins again ;)
Closes https://github.com/lxqt/lxqt-panel/issues/2113
=> Made auto-hiding on overlapping work under kwin_wayland

panel/lxqtpanel.cpp, panel/lxqtpanelapplication.cpp
This patch fixes three issues on Wayland:
* First, if a new panel was added to another screen, it wouldn't be positioned on that screen without a module restart; i.e., an on-the-fly screen positioning was impossible.
* Second, if the screen of a panel was removed and added again, that panel wouldn't be shown without a module restart.
* Finally, if the screen of a panel was removed, it wouldn't be moved to an existing screen without a module restart.
Closes https://github.com/lxqt/lxqt-panel/issues/2073
=> Fixed three bugs with multi-screen setups on Wayland

panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp, plugin-taskbar/lxqttaskbutton.cpp
This patch fixes two issues:
* On X11 and kwin_wayland, windows that were shown on all desktops wouldn't be shown on the taskbar if "Show only windows from desktop" was checked; and
* On kwin_wayland, auto-hiding on overlapping didn't work with such windows.
Fixes https://github.com/lxqt/lxqt-panel/issues/2186
=> Fixed taskbar when a window is shown on all desktops

panel/backends/ilxqtabstractwmiface.cpp, panel/backends/ilxqtabstractwmiface.h, panel/backends/lxqtdummywmbackend.cpp, panel/backends/lxqtdummywmbackend.h, panel/backends/lxqttaskbartypes.h, panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp, panel/backends/xcb/lxqtwmbackend_x11.cpp, panel/backends/xcb/lxqtwmbackend_x11.h, plugin-desktopswitch/desktopswitch.cpp, plugin-taskbar/lxqttaskbutton.cpp
The problem was that each backend may have a different enum for such windows — e.g., that of X11 is -1 — while the code assumed a value of zero for all.
=> Fixed handling of windows that are on all desktops

plugin-taskbar/lxqttaskbar.cpp
Checking the absolute visibility in `LXQtTaskBar::refreshPlaceholderVisibility()` caused a problem when an auto-hiding panel was hidden on Wayland.
Fixes https://github.com/lxqt/lxqt-panel/issues/2191
=> Check visibility of task buttons only relative to task-bar

plugin-mount/configuration.ui, plugin-sysstat/lxqtsysstatconfiguration.ui, plugin-worldclock/lxqtworldclockconfiguration.ui
Prefer en_US over en_GB in several translations. More people are familiar with en_US.
Translations should be able to be preserved no problem.
"Behaviour" and "Behavior" were both translated already. This deprecates "Behaviour".
=> Prefer en_US over en_GB in root translations

plugin-qeyes/qeyeswidget.cpp
A small patch to fix pupil position when mouse pointer is on a center line inside an eye
=> plugin-qeyes: fix pupil position when pointer is in the center of an eye

plugin-dom/domplugin.cpp
`"Panel DOM Tree"` is already translated here: https://github.com/isf63/lxqt-panel/blob/26c8aa1d66086f994c83bbb139652994bd5d058b/plugin-dom/treewindow.ui#L14
=> plugin-dom: Add tooltip

panel/lxqtpanel.cpp, panel/plugin.cpp
LXQt Panel wrote heavily to its config file on startup for no good reason. Most of those redundant writings were done in `Plugin::saveSettings()`, for every active plugin.
By "redundant" I mean that the config file does not change after being written to. That may be acceptable on some occasions, but not on startup.
=> Prevent redundant writing to config file on startup

plugin-mainmenu/lxqtmainmenuconfiguration.ui, plugin-networkmonitor/lxqtnetworkmonitorconfiguration.ui, plugin-sensors/lxqtsensorsconfiguration.ui, plugin-spacer/spacerconfiguration.ui
Some fixes to lxqt-panel plugins config dialogs
Affected files:
plugin-mainmenu/lxqtmainmenuconfiguration.ui
plugin-networkmonitor/lxqtnetworkmonitorconfiguration.ui plugin-sensors/lxqtsensorsconfiguration.ui
plugin-spacer/spacerconfiguration.ui
=>  Reorder XML .ui files to correct tab orders for plugin config dialogs

panel/lxqtpanel.cpp, panel/lxqtpanel.h, panel/lxqtpanelapplication.cpp, panel/lxqtpanelapplication.h
The main reason behind this change is that screen setting by using numbers may not work with all Wayland compositors.
With this patch, and on Wayland,
* The screen names are used for determining where the panels should be shown;
* A panel is not moved to another screen when its screen is disconnected (unlike on X11);
* If the screen assigned to a panel is not connected on startup, that panel won't be created, but it will be created as soon as its corresponding screen is connected.
IMPORTANT NOTE: Since I couldn't test this patch, I made it based on some assumptions. For example, I don't know if Qt or the compositor hides a panel, automatically moves it to another screen, or just causes a crash when its screen is unplugged. Here, I've *assumed* that it hides the panel. So, the patch should …
=> Handle Wayland screens by using their names

plugin-fancymenu/lxqtfancymenuwindow.cpp
Home and End aren't enabled for the views because they can be used in the filter entry (even without a filter, they would be confusing).
NOTE: This is not related to the PR but is worth mentioning: Although the logic of using keyboard is correct, it can still be confusing to the user, especially because there's no visual clue about the focused view. We might want to do something about it later.
=> Enabled PageDown/PageUp for Fancy Menu

plugin-fancymenu/lxqtfancymenuconfiguration.ui, plugin-mainmenu/lxqtmainmenuconfiguration.ui
The properties have the same default values as what they were set to.
The alignment looked odd (but arguably is a matter of taste.)
=> mainmenu,fancymenu: Remove redundant QGroupBox .ui properties and AlignVCenter

plugin-worldclock/lxqtworldclock.cpp, plugin-worldclock/lxqtworldclock.h, plugin-worldclock/lxqtworldclockconfiguration.cpp, plugin-worldclock/lxqtworldclockconfiguration.ui
All timezones are shown on a popup by middle clicking the clock, and wheel switching may make you go to bed at 8 pm because you may have done it inadvertently, especially when the clock is near the desktop switcher.
The default is as before.
NOTE: Please don't merge before the release of 2.2.0.
=> Made timezone switch by mouse wheel optional in clock

plugin-sensors/resources/sensors.desktop.in
Adds an (okay) icon to plugin-sensors' plugin entry, previously there was none.
Icon exists in some KDE icon themes such as Breeze.
=> Add plugin-sensors plugin instance icon

plugin-quicklaunch/quicklaunchbutton.cpp, plugin-taskbar/lxqttaskbutton.cpp
Since the destiny of `QDrag` depends on external factors after `QDrag::exec()`, it shouldn't be used without a safeguard after that call.
=> Guard `QDrag` with `QPointer` to prevent DND crash

panel/backends/wayland/wlroots/lxqttaskbarwlrwm.h, panel/backends/wayland/wlroots/lxqtwmbackend_wlr.cpp, panel/backends/wayland/wlroots/lxqtwmbackend_wlr.h
This logic is followed:
* On showing desktop, all of the currently handled windows are minimized.
* On restoring windows, only those windows that were minimized by showing desktop are restored, i.e., if a window is minimized *before or after* showing desktop, it won't be restored.
* On restoring windows, the previously focused window is focused again (if still existing).
* If all windows that were minimized on showing desktop are unminimized or closed by the user, clicking the widget will show desktop again.
I didn't find a reliable way of restoring the order of the windows — `lastActivated` didn't work well after restoring windows.
=> Implemented "Show Desktop" in wlroots backend

panel/backends/wayland/wlroots/lxqttaskbarwlrwm.cpp, panel/backends/wayland/wlroots/lxqtwmbackend_wlr.cpp, panel/backends/wayland/wlroots/lxqtwmbackend_wlr.h
The Z-order (= overlapping order in stacking WMs) is restored based on the activation time. For that, the one-millisecond limitation should be circumvented because multiple windows may be unminimized and activated by the code in less than that interval.
=> Restore Z-order on toggling desktop-showing with wlroots

panel/backends/wayland/kwin_wayland/lxqttaskbarplasmawindowmanagment.h, panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp, panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.h
At least there were two problems in KWin's handling of showing desktop: it didn't minimize pcmanfm-qt's windows, and it minimized what it shouldn't, e.g., the windows on the bottom layer or Conky.
Here I circumvented KWin's handling of showing desktop by doing it directly, as I did for the wlroots backend but with small changes. One good thing about KWin is that it doesn't automatically focus a window on unminimizing it. So, the implementation got even better, IMO.
NOTE: kwin_x11 has had exactly the same problems for a long time, but I'm not motivated to log into X11 and make a workaround there — at least not for now ;)
=> Workaround for kwin_wayland's problems in showing desktop

panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp
In a rare case, its absence created a permanent task-button that had no window.
=> Added a missing removal signal to kwin_wayland backend

plugin-mount/configuration.cpp, plugin-mount/lxqtmountplugin.cpp
In other words, the option "Popup menu" is removed under Wayland. If it's selected on X11 or by editing the config file manually, the selection won't change, but it will be treated as "Show info" and displayed as such by the config dialog.
The reason is an old problem of Qt+Wayland: Before the first input (mouse) interaction with the app, Wayland displays its popup as a standalone window, e.g., decorated under stacking compositors. Worse than that, if the user lets the popup disappear by itself without clicking anywhere (the code has a timer for it), the first click on the mount button will cause a crash (without backtrace).
NOTE:
I've encountered similar Wayland issues elsewhere, e.g., in `QClipboard`. Their common denominator has been QtWayland's dumbness before the first input …
=> Disabled automatic showing of mount popup on Wayland

panel/backends/wayland/wlroots/lxqttaskbarwlrwm.cpp, panel/backends/wayland/wlroots/lxqtwmbackend_wlr.cpp, plugin-taskbar/lxqttaskgroup.cpp
In addition, the task-bar code had a problem that is fixed here:
When window grouping was enabled and only windows from the current screen/desktop were shown, the checked state of task buttons could be wrong if one window inside a group was sent to another screen/desktop.
I think this issue was very old and existed on X11 too but never reported. Anyway, a thorough test under X11 is really needed.
Closes https://github.com/lxqt/lxqt-panel/issues/2091
=> Completed showing current screen windows in wlroots taskbar

plugin-desktopswitch/desktopswitchbutton.cpp
The reason is that urgencies may be added and removed instantly, while repolishing can be expensive and cause blinking.
Closes https://github.com/lxqt/lxqt-panel/issues/2294
=> Added a 50-ms delay before making desktop switcher urgent

plugin-showdesktop/showdesktop.cpp, plugin-showdesktop/showdesktop.h
fixes #2307 
Note: using the same "hardcoded" delay value of 700ms as in taskbar for raising windows
=> showdesktop: Add show/hide desktop action on drag&drop

panel/backends/ilxqtabstractwmiface.h, panel/backends/lxqtdummywmbackend.cpp, panel/backends/lxqtdummywmbackend.h, panel/backends/wayland/CMakeLists.txt, panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp, panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.h, panel/backends/wayland/wayfire/CMakeLists.txt, panel/backends/wayland/wayfire/lxqtwmbackend_wf.cpp, panel/backends/wayland/wayfire/lxqtwmbackend_wf.h, panel/backends/wayland/wayfire/wayfire-common.cpp, panel/backends/wayland/wayfire/wayfire-common.h, panel/backends/wayland/wlroots/lxqtwmbackend_wlr.cpp, panel/backends/xcb/lxqtwmbackend_x11.cpp, panel/backends/xcb/lxqtwmbackend_x11.h, panel/ilxqtpanel.h, panel/lxqtpanel.h, plugin-desktopswitch/desktopswitch.cpp, plugin-desktopswitch/desktopswitch.h, plugin-desktopswitch/desktopswitchconfiguration.cpp, plugin-taskbar/lxqttaskbarconfiguration.cpp, plugin-taskbar/lxqttaskbutton.cpp
The credit goes to @marcusbritanicus for writing the core code in https://github.com/lxqt/lxqt-panel/pull/2280.
Known issues that may be fixed later in other PRs:
1. https://github.com/lxqt/lxqt-panel/pull/2280#issuecomment-3092537751
2. ~I disabled "Move To Next/Previous Monitor" because it didn't work (the error message was that the method "wsets/send-view-to-wset" wasn't found). I also kept its state contingent on `LXQtTaskBarBackendAction::Move`, which isn't supported by this backend for now.~
=> Wayfire backend (based on Marcus' patch)

plugin-fancymenu/lxqtfancymenu.cpp, plugin-fancymenu/lxqtfancymenuconfiguration.cpp
The base name is the name minus the prefix (`lxqt-` for LXQt), which is added by `libqtxdg` depending on `XDG_MENU_PREFIX`.
=> Accept menu file base-name in Fancy Menu

plugin-cpuload/lxqtcpuloadconfiguration.ui
Remove AlignVCenter (looks odd) and redundant properties.
See also https://github.com/lxqt/lxqt-panel/pull/2249
=> plugin-cpuload: Remove groupbox properties and AlignVCenter

plugin-dom/treewindow.ui, plugin-worldclock/lxqtworldclockconfigurationmanualformat.ui
- `<property name="geometry">` tags deleted for non- top-level widgets (Qt Designer remnants.)
- Geometry tag W x H rounded for top-level (windows) to the nearest `20` (they often were odd numbers, e.g. `139`.)
=> Delete widget (non- top-level) geometry tags

panel/config/configplacement.cpp, panel/config/configstyling.cpp, plugin-cpuload/lxqtcpuloadconfiguration.cpp, plugin-customcommand/lxqtcustomcommand.cpp, plugin-desktopswitch/desktopswitchconfiguration.cpp, plugin-directorymenu/directorymenuconfiguration.cpp, plugin-fancymenu/lxqtfancymenuconfiguration.cpp, plugin-kbindicator/src/kbdstateconfig.cpp, plugin-mainmenu/actionview.cpp, plugin-mainmenu/lxqtmainmenuconfiguration.cpp, plugin-networkmonitor/lxqtnetworkmonitorconfiguration.cpp, plugin-sensors/lxqtsensorsconfiguration.cpp, plugin-statusnotifier/statusnotifierconfiguration.cpp, plugin-taskbar/lxqttaskbarconfiguration.cpp, plugin-volume/lxqtvolumeconfiguration.cpp, plugin-worldclock/lxqtworldclockconfiguration.cpp
With Qt6, signals/slots are normally no longer overloaded. Therefore no disambiguation is needed.
In a couple of places `QOverload<>::of(` was still needed.
=> Remove unneeded QOverloads for connect() (Qt5 → Qt6)

plugin-fancymenu/lxqtfancymenuappmap.cpp, plugin-fancymenu/lxqtfancymenuappmap.h
This fixes the problem that entries starting with non-English characters were placed at the end of the All Applications menu.
It also fixes the case when two apps had the same name and only one of them appeared in the list.
Note that there is another pull request to fix the sorting of the other categories: https://github.com/lxqt/libqtxdg/pull/317
This pull request is needed for the All Applications list.
=> fancymenu: Use locale-aware sorting for app list

plugin-customcommand/lxqtcustomcommandconfiguration.cpp
closes #2346 
Replaced `tr` with `LXQtCustomCommandConfiguration::tr`, Qt requires a "context" for the translation strings, so when declared outside of the class it needs to call `tr` from the class to be used as the "context"
https://doc.qt.io/qt-6/i18n-source-translation.html
Also removed one word to avoid having one sentence separated into 2 translations strings, to maybe avoid issues with translations where the ordering of words might be different
=> customcommand: fix translation strings
