lxqt/lxqt-panel

- panel/lxqtpanel.cpp
- panel/plugin.cpp
Improve the user experience a little bit.
> Add missing action icons to the panel popup menu

- plugin-desktopswitch/desktopswitch.cpp
> Fixes mouse wheel on DesktopSwitch not functioning properly.

- CMakeLists.txt
- plugin-spacer/CMakeLists.txt
- plugin-spacer/resources/spacer.desktop.in
- plugin-spacer/spacer.cpp
- plugin-spacer/spacer.h
- plugin-spacer/spacerconfiguration.cpp
- plugin-spacer/spacerconfiguration.h
- plugin-spacer/spacerconfiguration.ui
Width is configurable, style can be changed in theme.
Fixes lxde/lxqt#394.
> new spacer plugin/widget

- plugin-taskbar/lxqttaskbar.cpp
This will fix the bug in taskbar when the panel is vertical.
Fixes lxde/lxqt#511.
> Fixing drag and drop of running programs' icons when panel is vertical

- CMakeLists.txt
- plugin-mount/CMakeLists.txt
- plugin-mount/actions/deviceaction.cpp
- plugin-mount/actions/deviceaction.h
- plugin-mount/actions/deviceaction_info.cpp
- plugin-mount/actions/deviceaction_info.h
- plugin-mount/actions/deviceaction_menu.cpp
- plugin-mount/actions/deviceaction_menu.h
- plugin-mount/actions/deviceaction_nothing.cpp
- plugin-mount/actions/deviceaction_nothing.h
- plugin-mount/lxqtmountplugin.cpp
- plugin-mount/lxqtmountplugin.h
- plugin-mount/menudiskitem.cpp
- plugin-mount/menudiskitem.h
- plugin-mount/popup.cpp
- plugin-mount/popup.h
from lxde/lxqt#95 got here... as @jleclanche suggested move to KF5Solid
> plugin-mount: switch from liblxqt-mount to KF5Solid

- panel/lxqtpanelapplication.cpp
- panel/lxqtpanelapplication.h
> panel: connected cleanup to signal aboutToQuit

- plugin-networkmonitor/translations/networkmonitor_cs.desktop
- plugin-networkmonitor/translations/networkmonitor_cs_CZ.desktop
czech translation for lxde/lxqt#409
> plugin-networkmonitor: fixed Czech translation

- panel/config/configpaneldialog.cpp
- panel/lxqtpanel.cpp
- plugin-desktopswitch/desktopswitch.cpp
- plugin-kbindicator/lxqtkbindicator.h
- plugin-mainmenu/lxqtmainmenu.cpp
- plugin-showdesktop/showdesktop.cpp
- plugin-taskbar/lxqttaskbar.h
- plugin-taskbar/lxqttaskbutton.cpp
as done in lxde/liblxqt/pull/36
> remove KF5/ prefix from includes

- plugin-dom/treewindow.cpp
- plugin-dom/treewindow.h
- plugin-dom/treewindow.ui
Showing all properties of widget -> usable for quick debugging ...
> plugin-dom: added all widget's properties view

- plugin-taskbar/lxqttaskbar.cpp
- plugin-taskbar/lxqttaskbar.h
- plugin-taskbar/lxqttaskbutton.cpp
- plugin-taskbar/lxqttaskbutton.h
- plugin-taskbar/lxqttaskgroup.cpp
- plugin-taskbar/lxqttaskgroup.h
> [wip] plugin-taskbar: optimized window icon geometry handling

- CMakeLists.txt
- panel/plugin.cpp
- plugin-spacer/spacer.h
> Make "spacer" a static plugin.

- plugin-volume/volumepopup.cpp
> plugin-volume: more obvious popup buttons

- panel/translations/lxqt-panel_ro_RO.ts
- plugin-clock/translations/clock_ro_RO.desktop
- plugin-clock/translations/clock_ro_RO.ts
- plugin-cpuload/translations/cpuload_ro_RO.desktop
- plugin-cpuload/translations/cpuload_ro_RO.ts
- plugin-desktopswitch/translations/desktopswitch_ro_RO.ts
- plugin-networkmonitor/translations/networkmonitor_ro_RO.desktop
- plugin-networkmonitor/translations/networkmonitor_ro_RO.ts
This PR updates faulty romanian translations and adds missing ones.
> Romanian translations

- panel/translations/lxqt-panel.ts
- panel/translations/lxqt-panel_de.ts
> Updated german translation.

- plugin-sysstat/lxqtsysstat.cpp
> plugin-sysstat: added tooltip information

- plugin-mainmenu/lxqtmainmenu.cpp
- plugin-mainmenu/lxqtmainmenu.h
> Set mainmenu icon size acording to used font

- plugin-statusnotifier/CMakeLists.txt
- plugin-statusnotifier/sniasync.cpp
- plugin-statusnotifier/sniasync.h
- plugin-statusnotifier/statusnotifierbutton.cpp
- plugin-statusnotifier/statusnotifierbutton.h
- plugin-statusnotifier/statusnotifierwidget.cpp
Avoids GUI blocking of panel in case (malicious) StatusNotifierItem application is not responding
see lxde/lxqt#708
> plugin-statusnotifier: getting of all StatusNotifierItem properties async

- plugin-taskbar/lxqttaskbar.cpp
- plugin-taskbar/lxqttaskbar.h
- plugin-taskbar/lxqttaskbutton.cpp
- plugin-taskbar/lxqttaskgroup.cpp
- plugin-taskbar/lxqttaskgroup.h
This sould resolve problems with moving taskbar buttons.
closes lxde/lxqt#681
> taskbar: Enhance moving buttons

- plugin-taskbar/lxqttaskbar.cpp
- plugin-taskbar/lxqttaskbar.h
- plugin-taskbar/lxqttaskbutton.cpp
- plugin-taskbar/lxqttaskbutton.h
(this needs the lxde/liblxqt#67)
> taskbar: Add visual effect to button move

- plugin-taskbar/lxqttaskbutton.cpp
Set the "hotSpot" of icon for DnD based on panel's position.
> taskbar: Enhance show icon for moving

- panel/config/addplugindialog.cpp
- panel/config/configpaneldialog.cpp
- panel/lxqtpanel.cpp
- panel/lxqtpanelapplication.cpp
- panel/panelpluginsmodel.cpp
- panel/plugin.cpp
- plugin-desktopswitch/desktopswitch.cpp
- plugin-kbindicator/src/kbdstateconfig.cpp
- plugin-mainmenu/lxqtmainmenuconfiguration.cpp
- plugin-mount/configuration.cpp
- plugin-mount/lxqtmountplugin.cpp
- plugin-mount/lxqtmountplugin.h
- plugin-spacer/spacerconfiguration.cpp
- plugin-statusnotifier/sniasync.cpp
- plugin-statusnotifier/statusnotifierbutton.cpp
- plugin-statusnotifier/statusnotifieriteminterface.h
- plugin-sysstat/lxqtsysstat.cpp
- plugin-sysstat/lxqtsysstatconfiguration.cpp
- plugin-taskbar/lxqttaskbarconfiguration.cpp
- plugin-taskbar/lxqttaskgroup.cpp
- plugin-volume/volumepopup.cpp
Replacing QStringLiteral by (QLatin1String/QString)
See bug report: https://bugreports.qt.io/browse/QTBUG-49061
> Workaround to the QStringLiteral static finalization bug

- plugin-mainmenu/lxqtmainmenu.cpp
- plugin-mainmenu/lxqtmainmenuconfiguration.cpp
- plugin-mainmenu/lxqtmainmenuconfiguration.h
- plugin-mainmenu/lxqtmainmenuconfiguration.ui
ref. lxde/lxqt#892 & lxde/lxqt#720
> mainmenu: Use configurable icon

- plugin-taskbar/lxqttaskbar.cpp
We need to propagate windowChanged to each group if WindowClass changes
closes lxde/lxqt#586
> taskbar: Fix multiple groups when WindowClass changes

- plugin-tray/trayicon.cpp
> plugin-tray: Fix native window sizes for high DPI devices

- plugin-mainmenu/lxqtmainmenu.cpp
- plugin-mainmenu/lxqtmainmenu.h
- plugin-mainmenu/lxqtmainmenuconfiguration.cpp
- plugin-mainmenu/lxqtmainmenuconfiguration.ui
For correctly showing icon path in configuration we need to know if we should override icon set by style sheet..
fixes lxde/lxqt#931
> mainmenu: Fix showing icon path in configuration

- plugin-tray/lxqttray.cpp
- plugin-tray/trayicon.cpp
- plugin-tray/trayicon.h
> Tray delay

- plugin-volume/lxqtvolumeconfiguration.cpp
> volume: Avoid infinite cycle in config dialog

- panel/config/configpluginswidget.cpp
- panel/panelpluginsmodel.cpp
- panel/panelpluginsmodel.h
> panel: Correct PanelPluginsModel logic

- panel/ilxqtpanel.h
- panel/lxqtpanel.cpp
- panel/lxqtpanel.h
Hey guys,
I have continued to write code documentation. Now, I have dealt with ILXQtPanel and LXQtPanel. I hope that everything can be clearly understood.
Best regards
> Comments, documentation and code beautifications

- panel/CMakeLists.txt
- panel/ilxqtpanelplugin.h
- panel/plugin.cpp
- panel/pluginsettings.cpp
- panel/pluginsettings.h
- panel/pluginsettings_p.h
- plugin-cpuload/lxqtcpuload.cpp
- plugin-mainmenu/lxqtmainmenuconfiguration.cpp
- plugin-quicklaunch/lxqtquicklaunch.cpp
- plugin-screensaver/panelscreensaver.cpp
- plugin-showdesktop/showdesktop.cpp
- plugin-statusnotifier/statusnotifierwidget.cpp
> PluginSettings: Make settings object/class public

- plugin-taskbar/lxqttaskbar.cpp
- plugin-taskbar/lxqttaskbar.h
- plugin-taskbar/lxqttaskbarconfiguration.cpp
- plugin-taskbar/lxqttaskbarconfiguration.ui
- plugin-taskbar/lxqttaskbutton.cpp
- plugin-taskbar/lxqttaskbutton.h
- plugin-taskbar/lxqttaskgroup.cpp
- plugin-taskbar/lxqttaskgroup.h
> taskbar: Use icon from theme (based on windowClass)

- plugin-mainmenu/lxqtmainmenu.cpp
- plugin-mainmenu/lxqtmainmenu.h
> mainmenu: Add search/hide posibility

- plugin-mainmenu/CMakeLists.txt
- plugin-mainmenu/actionview.cpp
- plugin-mainmenu/actionview.h
- plugin-mainmenu/lxqtmainmenu.cpp
- plugin-mainmenu/lxqtmainmenu.h
- plugin-mainmenu/lxqtmainmenuconfiguration.cpp
- plugin-mainmenu/lxqtmainmenuconfiguration.ui
1. just filter entries in the herarchy
2. show matching entries in top menu (list)
Both can be used simulatenously.
Ref. lxde/lxqt#101
> mainmenu: Add configurable way of search

- plugin-tray/lxqttray.cpp
- plugin-tray/lxqttray.h
> tray: Fix SEGFAULT on stop

- panel/lxqtpanel.cpp
- panel/lxqtpanel.h
> panel: Add "Lock Panel" functionality

- panel/plugin.cpp
- plugin-quicklaunch/lxqtquicklaunch.cpp
- plugin-statusnotifier/statusnotifierbutton.cpp
- plugin-worldclock/lxqtworldclockconfigurationtimezones.cpp
We should use const references whenever possible.
> Use const references with the foreach iterator

- plugin-directorymenu/directorymenu.cpp
> plugin/directorymenu: Removes no use code

- plugin-mainmenu/xdgcachedmenu.cpp
- plugin-mainmenu/xdgcachedmenu.h
Thanks @LStranger!
Fixes lxde/lxqt#582.
> Respect the OnlyShowIn property for menu entries when using menu-cache

- panel/lxqtpanellayout.cpp
- plugin-taskbar/lxqttaskbar.cpp
This needs lxde/liblxqt#97
Should go after the #356
> taskbar: Remove orientation specific logic for DnD

- plugin-desktopswitch/desktopswitch.cpp
With this we will correctly support RightToLeft layout direction.
Another piece of puzzle for lxde/lxqt#421
> LXQtPanelLayout: Take layoutDirection into account

- plugin-mainmenu/lxqtmainmenu.cpp
> mainmenu: Fix show/hide actions after menu rebuild

- plugin-sensors/lxqtsensors.cpp
> Fix some sensor issues

- plugin-mainmenu/lxqtmainmenu.cpp
...with Breeze theme.
closes lxde/lxqt#1109
> mainmenu: Workaround transparent search

- plugin-taskbar/lxqttaskbar.cpp
- plugin-taskbar/lxqttaskbar.h
- plugin-taskbar/lxqttaskbarconfiguration.cpp
- plugin-taskbar/lxqttaskbarconfiguration.ui
Required in https://github.com/lxde/lxqt/issues/104#issuecomment-257013010
> taskbar: Add "raise on wheel" configuration

- panel/plugin.cpp
- plugin-kbindicator/kbindicator-plugin.cpp
- plugin-tray/lxqttrayplugin.h
> Enabling testing on weston

- panel/plugin.cpp
- plugin-mount/actions/deviceaction.cpp
- plugin-mount/actions/deviceaction.h
- plugin-mount/lxqtmountplugin.cpp
- plugin-mount/popup.cpp
- plugin-mount/popup.h
> Mount notification fixes

- panel/config/configpanelwidget.cpp
- panel/config/configpanelwidget.h
- panel/config/configpanelwidget.ui
- panel/lxqtpanel.cpp
- panel/lxqtpanel.h
..to allow maximized windows go under the panel (if the user wants to).
closes lxde/lxqt#1221
> panel: Make space reserve on display configurable

- plugin-mainmenu/lxqtmainmenu.cpp
- plugin-mainmenu/lxqtmainmenu.h
- plugin-mainmenu/lxqtmainmenuconfiguration.cpp
- plugin-mainmenu/lxqtmainmenuconfiguration.ui
> mainmenu: Clear search upon show (configurable)

- plugin-mainmenu/lxqtmainmenu.cpp
> mainmenu: Add "true" translucency support

- plugin-volume/lxqtvolume.cpp
- plugin-volume/lxqtvolume.h
- plugin-volume/lxqtvolumeconfiguration.cpp
- plugin-volume/lxqtvolumeconfiguration.h
- plugin-volume/lxqtvolumeconfiguration.ui
> volume: Add all changes notifications (configurable)

- panel/main.cpp
> set Qt::AA_UseHighDpiPixmaps to true

- plugin-mainmenu/lxqtmainmenu.cpp
- plugin-mainmenu/xdgcachedmenu.cpp
- plugin-mainmenu/xdgcachedmenu.h
> Menu cache release

- plugin-volume/lxqtvolume.cpp
- plugin-volume/lxqtvolumeconfiguration.cpp
- plugin-volume/lxqtvolumeconfiguration.h
> volume: Do check for OSS availability in run-time

- plugin-worldclock/lxqtworldclock.cpp
- plugin-worldclock/lxqtworldclock.h
Fixes https://github.com/lxde/lxqt/issues/1245.
The time is checked every second but the clock text is updated only when needed.
> Fix clock text update

- plugin-clock/lxqtclock.cpp
..as the clock will be removed in next release.
ref. lxde/lxqt#312
IMO showing the message is enough. And we will not do any changes to `clock` plugin even if someone requests them.
> clock: Show deprecation message on startup/add

- plugin-quicklaunch/quicklaunchaction.cpp
- plugin-quicklaunch/quicklaunchaction.h
- plugin-quicklaunch/quicklaunchbutton.cpp
This is ~~a dirty~~ implementation of lxde/lxqt#1319 and needs the lxde/libqtxdg#142
@luis-pereira @tsujan @PCMan 
~~Should we somehow incorporate something like `XdgDesktopAction` into the libqtxdg?~~
closes lxde/lxqt#1319
> quicklaunch: Add "Desktop Action" support

- plugin-quicklaunch/quicklaunchbutton.cpp
fixes the issue mentioned here -> https://github.com/lxde/lxqt-panel/pull/435#issuecomment-335901449
> quicklaunch: Show popup menu aligned to clicked button

- plugin-kbindicator/CMakeLists.txt
Closes #1381.
Use in conjunction with https://github.com/lxde/lxqt-build-tools/pull/23.
> Use the new FindXKBCommon CMake module

- panel/ilxqtpanel.h
- panel/lxqtpanel.cpp
- panel/lxqtpanel.h
- plugin-clock/lxqtclock.cpp
>  lxqtpanel: Fix wrongly positioned popups

- panel/CMakeLists.txt
same as for session - make it easy for distributions to provide own configs
> move panel config to /usr/share/lxqt

- plugin-statusnotifier/CMakeLists.txt
Mark the DBUS_SOURCES files with SKIP_AUTOGEN
> cmake: Handle CMP0071

- plugin-mainmenu/xdgcachedmenu.cpp
this fix https://github.com/lxde/lxqt/issues/1431
> avoid inifinite recusion when no icon avaible.

- panel/lxqtpanel.cpp
- panel/pluginsettings.cpp
- plugin-kbindicator/src/x11/kbdlayout.cpp
- plugin-mainmenu/actionview.cpp
- plugin-mainmenu/lxqtmainmenu.cpp
- plugin-mount/popup.cpp
- plugin-quicklaunch/lxqtquicklaunch.cpp
- plugin-sysstat/lxqtsysstatconfiguration.cpp
- plugin-taskbar/lxqttaskbar.cpp
Deep copies are expensive and not needed here.
> Prevent possible container detachments

- panel/resources/panel.conf
This fixes the change introduced in a014248fdc9fbbd0972fb44b8b5d1776301a889b
> Fix worldclock in panel.conf

- CMakeLists.txt
- plugin-mainmenu/CMakeLists.txt
> Introduce option USE_MENU_CACHE, default OFF

- .gitattributes
- .gitignore
- .translation-update
- plugin-sysstat/translations/sysstat.ts
- plugin-sysstat/translations/sysstat_ca.ts
- plugin-sysstat/translations/sysstat_cs.ts
- plugin-sysstat/translations/sysstat_da.ts
- plugin-sysstat/translations/sysstat_de.ts
- plugin-sysstat/translations/sysstat_el.ts
- plugin-sysstat/translations/sysstat_es.ts
- plugin-sysstat/translations/sysstat_fr.ts
- plugin-sysstat/translations/sysstat_hu.ts
- plugin-sysstat/translations/sysstat_id.ts
- plugin-sysstat/translations/sysstat_it.ts
- plugin-sysstat/translations/sysstat_ja.ts
- plugin-sysstat/translations/sysstat_lt.ts
- plugin-sysstat/translations/sysstat_nl.ts
- plugin-sysstat/translations/sysstat_pl.ts
- plugin-sysstat/translations/sysstat_pt.ts
- plugin-sysstat/translations/sysstat_ru.ts
- plugin-sysstat/translations/sysstat_tr.ts
- plugin-sysstat/translations/sysstat_uk.ts
- plugin-sysstat/translations/sysstat_zh_CN.ts
Added not automagically moved sysstat translations
Added translation update handling
> Translation update

- plugin-volume/audiodevice.cpp
- plugin-volume/lxqtvolume.cpp
> volume: Do not auto-unmute on volume change

- panel/ilxqtpanel.h
- panel/ilxqtpanelplugin.h
- panel/lxqtpanel.cpp
- panel/lxqtpanel.h
- panel/lxqtpanellayout.cpp
- panel/lxqtpanellayout.h
- plugin-spacer/spacer.cpp
- plugin-spacer/spacer.h
- plugin-spacer/spacerconfiguration.cpp
- plugin-spacer/spacerconfiguration.h
- plugin-spacer/spacerconfiguration.ui
Add possibility for spacer plugin to be auto-expandable.
closes lxde/lxqt#1038
> WIP: Spacer expandable

- plugin-mainmenu/actionview.cpp
- plugin-mainmenu/actionview.h
- plugin-mainmenu/lxqtmainmenu.cpp
Closes https://github.com/lxqt/lxqt/issues/1617
> Also include exec name in filtering without menu-cache

- CMakeLists.txt
- autostart/CMakeLists.txt
- plugin-kbindicator/CMakeLists.txt
Use lxqt-build-tools (except CMAKE_MODULE_LINKER_FLAGS)
> Set cmake_minimum_required(VERSION 3.1.0 FATAL_ERROR)

- menu/translations/lxqt-leave_zh_TW.directory
- menu/translations/lxqt-settings_zh_TW.directory
@agaida: are those files managed by Weblate? I can't find them.
> Add zh_TW translations for lxqt-{leave,settings}.directory

- menu/translations/lxqt-leave_tr.directory
- menu/translations/lxqt-settings_tr.directory
Added missing **_tr.directory files
> desktop-directories

- panel/config/configpanelwidget.cpp
- panel/ilxqtpanel.h
- panel/ilxqtpanelplugin.h
- panel/lxqtpanel.cpp
- panel/panelpluginsmodel.cpp
- panel/plugin.cpp
- panel/windownotifier.cpp
- plugin-cpuload/lxqtcpuload.cpp
- plugin-desktopswitch/desktopswitch.cpp
- plugin-mount/actions/deviceaction_menu.cpp
- plugin-mount/actions/deviceaction_nothing.cpp
- plugin-mount/menudiskitem.cpp
- plugin-networkmonitor/lxqtnetworkmonitor.cpp
- plugin-quicklaunch/quicklaunchbutton.cpp
- plugin-statusnotifier/statusnotifierbutton.cpp
- plugin-taskbar/lxqtgrouppopup.cpp
- plugin-taskbar/lxqttaskgroup.cpp
- plugin-volume/alsaengine.cpp
- plugin-volume/ossengine.cpp
- plugin-volume/pulseaudioengine.cpp
- plugin-volume/volumebutton.cpp
- plugin-volume/volumepopup.cpp
- plugin-worldclock/lxqtworldclock.cpp
- fall through
- unused parameter
> build: Address compiler warnings

- plugin-worldclock/lxqtworldclock.cpp
> worldclock: Request size adjust in realign

- .ci/build.sh
- .travis.yml
Closes: https://github.com/lxqt/lxqt-panel/issues/1099
Ref: https://github.com/lxqt/lxqt/issues/1644
This is an adoption for a similar setup from qtermwidget. See https://github.com/lxqt/qtermwidget/pull/271 for previous discussions.
> Initial Travis CI setup

- README.md
By mistake "and" is written as "und"
> little error in README.md

- plugin-desktopswitch/desktopswitch.cpp
- plugin-desktopswitch/desktopswitch.h
- plugin-desktopswitch/desktopswitchconfiguration.cpp
- plugin-desktopswitch/desktopswitchconfiguration.ui
> desktopswitch: Add "only indicator" behavior (configurable)

- plugin-taskbar/lxqttaskbar.cpp
- plugin-taskbar/lxqttaskbarconfiguration.cpp
- plugin-taskbar/lxqttaskbutton.cpp
- plugin-taskbar/lxqttaskgroup.cpp
@tsujan - i hope i get the string parts useful - but no clue about the remaining things - the enums and windowclass
> Some manual string conversions

- plugin-quicklaunch/quicklaunchbutton.cpp
As suggested by @agaida.
The current translations are intact.
Closes https://github.com/lxqt/lxqt-panel/issues/1181
> Quick Launch: Added Ctrl+DND hint

- plugin-taskbar/lxqttaskbutton.cpp
Fixes https://github.com/lxqt/lxqt-panel/issues/1204
> Release mouse after task button DND

- .travis.yml
See commit messages in https://github.com/lxqt/qtermwidget/pull/303 for details.
> Fix building on Travis CI

- panel/CMakeLists.txt
Already defined in LXQtCompilerSettings.
> Remove (duplicated) string casts definitions

- plugin-cpuload/lxqtcpuloadconfiguration.cpp
> Remove deprecated trUtf8()

- plugin-kbindicator/src/content.cpp
> kbindicator: Set alignment for layout button

- plugin-sysstat/lxqtsysstatconfiguration.ui
Previously reported on weblate: https://weblate.lxqt.org/translate/lxqt/lxqt-panel-plugin-sysstat/en/?checksum=ec376aaa03144b54#comments
> lxqtsysstatconfiguration.ui: fix a minor typo

- panel/panelpluginsmodel.cpp
- plugin-mount/popup.cpp
- plugin-worldclock/lxqtworldclock.cpp
- plugin-worldclock/lxqtworldclockconfiguration.cpp
> Prevent range-for container detachment

- CMakeLists.txt
- plugin-backlight/CMakeLists.txt
- plugin-backlight/backlight.cpp
- plugin-backlight/backlight.h
- plugin-backlight/resources/backlight.desktop.in
- plugin-backlight/sliderdialog.cpp
- plugin-backlight/sliderdialog.h
- plugin-backlight/translations/backlight_es.desktop
This is a simple plugin to change the backlight of the display.
> Backlight plugin

- panel/translations/lxqt-panel_hu.ts
- plugin-colorpicker/translations/colorpicker_hu.desktop
- plugin-cpuload/translations/cpuload_hu.ts
- plugin-desktopswitch/translations/desktopswitch_hu.desktop
- plugin-directorymenu/translations/directorymenu_hu.ts
- plugin-kbindicator/translations/kbindicator_hu.ts
- plugin-mainmenu/translations/mainmenu_hu.desktop
- plugin-mainmenu/translations/mainmenu_hu.ts
- plugin-mount/translations/mount_hu.desktop
- plugin-mount/translations/mount_hu.ts
- plugin-networkmonitor/translations/networkmonitor_hu.desktop
- plugin-networkmonitor/translations/networkmonitor_hu.ts
- plugin-quicklaunch/translations/quicklaunch_hu.desktop
- plugin-quicklaunch/translations/quicklaunch_hu.ts
- plugin-sensors/translations/sensors_hu.ts
- plugin-showdesktop/translations/showdesktop_hu.desktop
- plugin-showdesktop/translations/showdesktop_hu.ts
- plugin-spacer/translations/spacer_hu.ts
- plugin-statusnotifier/translations/statusnotifier_hu.desktop
- plugin-sysstat/translations/sysstat_hu.desktop
- plugin-sysstat/translations/sysstat_hu.ts
- plugin-taskbar/translations/taskbar_hu.ts
- plugin-tray/translations/tray_hu.desktop
- plugin-tray/translations/tray_hu.ts
- plugin-volume/translations/volume_hu.ts
- plugin-worldclock/translations/worldclock_hu.ts
> Many Hungarian translations updated

- plugin-kbindicator/src/content.cpp
- plugin-kbindicator/src/kbdstateconfig.ui
- plugin-kbindicator/src/settings.cpp
Fixes https://github.com/lxqt/lxqt-panel/issues/1391
> Fixed keyboard indicator flag

- menu/desktop-directories/lxqt-settings.directory.in
The Encoding key is deprecated.
> Deleted `Encoding` key

- panel/translations/lxqt-panel_tr.ts
Updated Turkish translations for more regular Turkish.
> Update Turkish translations of panel

- plugin-backlight/translations/backlight_tr.desktop
- plugin-colorpicker/translations/colorpicker_tr.desktop
* Added Turkish translations of plugin-backlight.
* Added Turkish translations of plugin-colorpicker.
> Add Turkish translations

- plugin-kbindicator/src/kbdkeeper.cpp
- plugin-taskbar/lxqttaskbar.cpp
- plugin-taskbar/lxqttaskbutton.cpp
- plugin-taskbar/lxqttaskgroup.cpp
Using 0/nullptr is deprecated.
> Use QFlags default constructor

- plugin-statusnotifier/statusnotifierwidget.cpp
1. The icon of the show button is removed and `+` is set as its text to distinguish it from items.
2. The show button is made hidden when it's clicked and is shown again when needed (2 seconds after the mouse cursor leaves the widget).
3. The `clicked` signal is used for showing all items because the `released` signal could also be emitted when the cursor wasn't inside the widget, in which case, the items wouldn't be made hidden again.
@yan12125 
Since you're familiar with the code, I requested a review from you again. But, this time, it's only about a few changes.
> Enhancements to Status Notifier's show button

- panel/config/configpanelwidget.cpp
- panel/lxqtpanel.cpp
Documented to be faster.
Found by Clazy.
> Use static QFileInfo::exists()

- plugin-desktopswitch/desktopswitch.cpp
- plugin-directorymenu/directorymenuconfiguration.cpp
- plugin-sysstat/lxqtsysstatutils.cpp
Use the const versions.
It good practice and shuts up false positives.
> Don't call non-const member functions on temporaries

- panel/translations/lxqt-panel_it.ts
- panel/translations/lxqt-panel_ro_RO.ts
- plugin-desktopswitch/translations/desktopswitch_it.ts
- plugin-directorymenu/translations/directorymenu_it.ts
- plugin-kbindicator/translations/kbindicator_it.ts
- plugin-networkmonitor/translations/networkmonitor_it.ts
- plugin-quicklaunch/translations/quicklaunch_it.ts
- plugin-statusnotifier/translations/statusnotifier_it.ts
- plugin-sysstat/translations/sysstat_it.ts
- plugin-taskbar/translations/taskbar_it.ts
- plugin-tray/translations/tray_it.ts
- plugin-volume/translations/volume_it.ts
- plugin-worldclock/translations/worldclock_it.ts
Co-authored-by: Standreas <ste@vogliaditerra.com>
Translate-URL: http://135.181.85.100/projects/lxqt-panel/panel/it/
Translate-URL: http://135.181.85.100/projects/lxqt-panel/panel/ro/
Translate-URL: http://135.181.85.100/projects/lxqt-panel/plugin-desktopswitch/it/
Translate-URL: http://135.181.85.100/projects/lxqt-panel/plugin-directorymenu/it/
Translate-URL: http://135.181.85.100/projects/lxqt-panel/plugin-kbindindicator/it/
Translate-URL: http://135.181.85.100/projects/lxqt-panel/plugin-networkmonitor/it/
Translate-URL: http://135.181.85.100/projects/lxqt-panel/plugin-quicklaunch/it/
Translate-URL: http://135.181.85.100/projects/lxqt-panel/plugin-sysstat/it/
Translate-URL: http://135.181.85.100/projects/lxqt-panel/plugin-taskbar/it/
Translate-URL: …
> Weblate commits

- plugin-mainmenu/lxqtmainmenu.cpp
Added actions from desktop file and icons to the new right click menu.
> add actions and icons to right click menu

- plugin-taskbar/lxqttaskgroup.cpp
Fixes https://github.com/lxqt/lxqt-panel/issues/1474
> Fixed grouped task button popup in a special case

- plugin-kbindicator/src/kbdstateconfig.cpp
- plugin-quicklaunch/quicklaunchaction.cpp
- plugin-volume/volumebutton.cpp
> Drop QProcess deprecated members

- menu/translations/lxqt-leave.directory.yaml
- menu/translations/lxqt-leave_cs.directory.yaml
- menu/translations/lxqt-leave_de.directory.yaml
- menu/translations/lxqt-leave_es.directory.yaml
- menu/translations/lxqt-leave_eu.directory.yaml
- menu/translations/lxqt-leave_fr.directory.yaml
- menu/translations/lxqt-leave_gl.directory.yaml
- menu/translations/lxqt-leave_hr.directory.yaml
- menu/translations/lxqt-leave_hu.directory.yaml
- menu/translations/lxqt-leave_it.directory.yaml
- menu/translations/lxqt-leave_ja.directory.yaml
- menu/translations/lxqt-leave_lt.directory.yaml
- menu/translations/lxqt-leave_nl.directory.yaml
- menu/translations/lxqt-leave_pl.directory.yaml
- menu/translations/lxqt-leave_pt.directory.yaml
- menu/translations/lxqt-leave_ru.directory.yaml
- menu/translations/lxqt-leave_tr.directory.yaml
- menu/translations/lxqt-leave_zh_CN.directory.yaml
- menu/translations/lxqt-leave_zh_TW.directory.yaml
- menu/translations/lxqt-settings.directory.yaml
- menu/translations/lxqt-settings_ru.directory.yaml
"Comment" is nowhere  shown in menu categories.
Related: https://github.com/lxqt/lxqt/issues/1893
> fixed .yaml files

- plugin-mount/configuration.ui
Thanks to the Weblate user @scootergrisen for spotting it
> Fix a typo

- panel/config/configpaneldialog.cpp
- panel/config/configpanelwidget.cpp
- panel/config/configpanelwidget.ui
- panel/config/configpluginswidget.cpp
- panel/lxqtpanel.cpp
- panel/lxqtpanellayout.cpp
- panel/plugin.cpp
- panel/pluginmoveprocessor.cpp
> Move to Qt5 signal/slot syntax

- panel/lxqtpanel.cpp
- plugin-backlight/backlight.cpp
- plugin-backlight/sliderdialog.cpp
- plugin-colorpicker/colorpicker.cpp
- plugin-cpuload/lxqtcpuloadconfiguration.cpp
- plugin-desktopswitch/desktopswitch.cpp
- plugin-desktopswitch/desktopswitchconfiguration.cpp
plugins: backlight, colorpicker, cpuload, desktopswitch.
First 3 should be easy switches. Desktopswitch has something more to
be checked
> Qt5 signal/slot, 2nd step

- plugin-directorymenu/directorymenu.cpp
- plugin-directorymenu/directorymenuconfiguration.cpp
- plugin-dom/domplugin.cpp
- plugin-dom/domtreeitem.cpp
- plugin-dom/treewindow.cpp
- plugin-kbindicator/src/kbdkeeper.cpp
- plugin-kbindicator/src/kbdstateconfig.cpp
- plugin-kbindicator/src/kbdwatcher.cpp
- plugin-mainmenu/lxqtmainmenu.cpp
- plugin-mainmenu/lxqtmainmenuconfiguration.cpp
Plugins: directorymenu, dom, kbindicator, mainmenu
> Qt5 signal/slot, 3rd step

- plugin-mount/menudiskitem.cpp
- plugin-mount/popup.cpp
- plugin-networkmonitor/lxqtnetworkmonitorconfiguration.cpp
Plugins: mount, networkmonitor (just two, as promised)
:)
> Qt5 signal/slots change

- plugin-quicklaunch/lxqtquicklaunch.cpp
- plugin-quicklaunch/quicklaunchaction.cpp
- plugin-quicklaunch/quicklaunchbutton.cpp
- plugin-sensors/lxqtsensors.cpp
- plugin-sensors/lxqtsensorsconfiguration.cpp
> Move to Qt5 signal/slot syntax (n-th patch) :)

- plugin-sysstat/lxqtsysstat.cpp
- plugin-sysstat/lxqtsysstat.h
- plugin-sysstat/lxqtsysstatcolours.cpp
- plugin-sysstat/lxqtsysstatconfiguration.cpp
I also ifdef(ed) deprecated code and changed a C style preprocessor
call to a more readable (IMHO) QMap iteration
> plugin: sysstat, move to Qt5 signal/slot system

- plugin-taskbar/lxqttaskbar.cpp
- plugin-taskbar/lxqttaskbarconfiguration.cpp
- plugin-taskbar/lxqttaskbutton.cpp
- plugin-taskbar/lxqttaskgroup.cpp
porting to Qt 5.15 code
style fixes
> Plugin taskbar: move to Qt5 signal/slot syntax

- plugin-tray/lxqttrayconfiguration.cpp
- plugin-volume/alsaengine.cpp
- plugin-volume/lxqtvolume.cpp
- plugin-volume/lxqtvolumeconfiguration.cpp
- plugin-volume/pulseaudioengine.cpp
- plugin-volume/volumebutton.cpp
- plugin-volume/volumepopup.cpp
plugins: tray (1 line), volume
> Qt5 signal/slot syntax

- plugin-statusnotifier/statusnotifierbutton.cpp
- plugin-worldclock/lxqtworldclock.cpp
- plugin-worldclock/lxqtworldclockconfiguration.cpp
- plugin-worldclock/lxqtworldclockconfigurationmanualformat.cpp
- plugin-worldclock/lxqtworldclockconfigurationtimezones.cpp
plugin: worldclock
Port to Qt 5.15: remove QWheelEvent::delta() usage
> Move to Qt5 signal/slot syntax panel series: last commit

- plugin-directorymenu/directorymenu.cpp
- plugin-volume/alsaengine.cpp
Closes https://github.com/lxqt/lxqt-panel/issues/1606
> Fixed compilation against Qt < 5.15

- plugin-mainmenu/lxqtmainmenu.cpp
Fixes https://github.com/lxqt/lxqt-panel/issues/1558
> Fixed the keypad navigation in main menu

- plugin-customcommand/custombutton.h
@tsujan i forgot to change this on custombutton header
> fix custombutton header

- plugin-statusnotifier/statusnotifierbutton.cpp
`svg` and `xpm` are also checked, in addition to `png`.
> Status Notifier: Consider icon names that end with a valid extension

- panel/CMakeLists.txt
- panel/config/configpaneldialog.cpp
- panel/config/configpaneldialog.h
- panel/config/configplacement.cpp
- panel/config/configplacement.h
- panel/config/configplacement.ui
- panel/config/configstyling.cpp
- panel/config/configstyling.h
- panel/config/configstyling.ui
- panel/lxqtpanel.cpp
> Split panel config dialog into 3 sections

- panel/resources/panel.conf
Replaces https://github.com/lxqt/lxqt-panel/pull/1384
Related discussion: https://github.com/lxqt/lxqt/discussions/2163
> Add default settings, remove obsolete tray

- plugin-statusnotifier/CMakeLists.txt
- plugin-statusnotifier/statusnotifier.h
- plugin-statusnotifier/statusnotifierproxy.cpp
- plugin-statusnotifier/statusnotifierproxy.h
- plugin-statusnotifier/statusnotifierwidget.cpp
- plugin-statusnotifier/statusnotifierwidget.h
Supersedes #1618
@slidinghotdog Please, test/review/compare my changes.
Note: optimization for not duplicating icons, menus etc. is left for future PRs. We should create an issue for it, when this is merged.
> Allow multiple StatusNotifierWidgets, no.2

- plugin-directorymenu/directorymenu.cpp
- plugin-directorymenu/directorymenuconfiguration.cpp
- plugin-directorymenu/directorymenuconfiguration.h
- plugin-directorymenu/directorymenuconfiguration.ui
Closes https://github.com/lxqt/lxqt-panel/issues/1730
Also, two bugs are found and fixed here.
> Added options for button label and style of Directory Menu

- plugin-taskbar/lxqttaskbarconfiguration.cpp
- plugin-taskbar/lxqttaskbarconfiguration.h
Related to https://github.com/lxqt/lxqt-panel/issues/1741
> Fixed Reset button in taskbar config dialog

- menu/lxqt-applications-compact.menu
- menu/lxqt-applications-simple.menu
Offer users some alternatives.
> Adding 2 alternative menus

- plugin-colorpicker/CMakeLists.txt
- plugin-colorpicker/colorbutton.cpp
- plugin-colorpicker/colorbutton.h
- plugin-colorpicker/colorpicker.cpp
- plugin-colorpicker/colorpicker.h
- plugin-colorpicker/translations/colorpicker.desktop.yaml
- plugin-colorpicker/translations/colorpicker.ts
> New plugin Color Chooser, no.2

- plugin-dom/treewindow.cpp
> plugin-dom: Remove unused non trivial variable

- panel/config/addplugindialog.ui
Added the property to panel/config/addplugindialog.ui
Closes #1747.
> Enable clear button for Add Plugins search bar

- plugin-desktopswitch/desktopswitch.h
Fixes crashing on wayland etc.
Fixes #1903
> desktopswitch: Create dummy widget on unsupported platforms

- plugin-customcommand/lxqtcustomcommand.cpp
- plugin-customcommand/lxqtcustomcommand.h
- plugin-customcommand/lxqtcustomcommandconfiguration.cpp
- plugin-customcommand/lxqtcustomcommandconfiguration.h
- plugin-customcommand/lxqtcustomcommandconfiguration.ui
If anyone is interested.  This adds a checkbox for the customcommand widget to return an image instead of text.
An example is here...
https://github.com/niknah/panel-customcommand-scripts/blob/main/disk_image.sh
> Customcommand image

- panel/config/configstyling.cpp
> Add *.svg to background image picker dialog

- plugin-fancymenu/lxqtfancymenuwindow.cpp
- plugin-fancymenu/lxqtfancymenuwindow.h
… as far as the available screen geometry allows.
> Fit category view of Fancy Menu to its contents

- plugin-fancymenu/lxqtfancymenuappmap.cpp
- plugin-fancymenu/lxqtfancymenuwindow.cpp
Improve matching by doing case insensitive comparison.
Also tweak code to not move cursor while typing
> Improve FancyMenu search

- panel/config/addplugindialog.ui
Fixes https://github.com/lxqt/lxqt-panel/issues/1910
> Make default "add" button

- plugin-fancymenu/lxqtfancymenuconfiguration.ui
> Rename Popup > Layout

- plugin-fancymenu/lxqtfancymenuwindow.cpp
Fixes https://github.com/lxqt/lxqt-panel/issues/2015
> Ensure single auto-selection in Fancy Menu's app view

- plugin-fancymenu/lxqtfancymenu.cpp
> FancyMenu: fix favorites in config file

- plugin-fancymenu/lxqtfancymenuappmodel.cpp
- plugin-fancymenu/lxqtfancymenuappmodel.h
- plugin-fancymenu/lxqtfancymenuwindow.cpp
- plugin-fancymenu/lxqtfancymenuwindow.h
Closes #1986 
I wonder if there is more standard Qt code to do this. Also are comments clear enough or does it need better explanation of edge cases?
> FancyMenu: better key navigation

- plugin-fancymenu/lxqtfancymenuappmap.cpp
- plugin-fancymenu/lxqtfancymenuappmap.h
Closes https://github.com/lxqt/lxqt-panel/issues/2079
> Made Fancy Menu filtering work with exec name

- panel/backends/wayland/wlroots/lxqttaskbarwlrwm.cpp
Fixes https://github.com/lxqt/lxqt-panel/issues/2095
> Always consider minimized windows deactivated with wlroots

- panel/backends/wayland/wlroots/lxqttaskbarwlrwm.cpp
This PR fixes three (and maybe more) problems in context menus of wlroots task buttons, by providing a cleaner logic for setting the window states.
Previously,
* If a window was first maximized and then minimized, the Restore item would remain enabled after being clicked, although it could do nothing the next times (because the window would already be normal);
* If a window was maximized and then an overlay window (like dropdown qterminal) was shown and closed, the Maximize item would become enabled, although it could do nothing; and
* The same problem happened with minimizing and the Minimize item.
NOTE: As far as I tested, other probable issues in context menus were compositor-specific and not related to the code.
> Fixes for context menus of wlroots task buttons

- panel/backends/wayland/wlroots/lxqttaskbarwlrwm.cpp
Suddenly felt pedantic and couldn't resist it ;)
> Correct a comment typo

- plugin-worldclock/lxqtworldclockconfiguration.ui
Fixes https://github.com/lxqt/lxqt-panel/issues/2047
> Added information label about middle click

- panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp
This PR fixes the following problems:
* If a window was minimized by its task button's context menu, it couldn't be restored by that menu;
* If a window and its child dialog were minimized, only its child dialog would be restored;
* The Restore item was always enabled in the context menu; and
* The Maximize item was always disabled in the context menu.
Closes https://github.com/lxqt/lxqt-panel/issues/2093
> Fixed issues in kwin_wayland task buttons

- panel/backends/xcb/lxqtwmbackend_x11.cpp
- plugin-taskbar/lxqttaskbar.cpp
Fixes https://github.com/lxqt/lxqt-panel/issues/2130
> Fixed putting of same-class task buttons under Wayland

- panel/config/configplacement.ui
- plugin-desktopswitch/desktopswitchconfiguration.ui
- plugin-dom/treewindow.ui
- plugin-fancymenu/lxqtfancymenuconfiguration.ui
- plugin-kbindicator/src/kbdstateconfig.ui
- plugin-mainmenu/lxqtmainmenuconfiguration.ui
- plugin-networkmonitor/lxqtnetworkmonitorconfiguration.ui
- plugin-qeyes/qeyesconfigdialog.cpp
Same as https://github.com/lxqt/lxqt-panel/pull/2139 but for configuration windows.
> Capitalize remaining plugin config titles

- plugin-customcommand/translations/customcommand.desktop.yaml
See https://translate.lxqt-project.org/translate/lxqt-panel/-/en/?q=has:suggestion#suggestions
> Capitalizing cli

- panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp
See https://github.com/lxqt/lxqt-panel/pull/2153
> Added a missing version check

- panel/backends/xcb/lxqtwmbackend_x11.cpp
> Fixed changing of desktop names under X11

- plugin-fancymenu/lxqtfancymenu.cpp
- plugin-mainmenu/lxqtmainmenu.cpp
This is especially relevant under Wayland and fixes https://github.com/lxqt/lxqt-panel/issues/2177
> Take into account an empty shortcut in Fancy/Main Menu

- plugin-mainmenu/lxqtmainmenu.cpp
It was caused by https://github.com/lxqt/lxqt-panel/commit/2c263d58886c6f454aad0870a4417adfb49e5241
> Fixed a regression in keyboard navigation of Main Menu

- plugin-taskbar/lxqttaskbar.cpp
- plugin-taskbar/lxqttaskbar.h
- plugin-taskbar/lxqttaskbarconfiguration.cpp
- plugin-taskbar/lxqttaskbarconfiguration.ui
Closes https://github.com/lxqt/lxqt-panel/issues/1790
> Added exclusion list to taskbar config

- plugin-kbindicator/translations/kbindicator.desktop.yaml
Fixes  https://github.com/lxqt/lxqt-panel/issues/2203
> Added X11-only info for kbindicator

- plugin-customcommand/lxqtcustomcommand.cpp
- plugin-customcommand/lxqtcustomcommand.h
- plugin-customcommand/lxqtcustomcommandconfiguration.cpp
- plugin-customcommand/lxqtcustomcommandconfiguration.h
- plugin-customcommand/lxqtcustomcommandconfiguration.ui
Also, cleaned up the code.
Closes https://github.com/lxqt/lxqt-panel/issues/2209
> Added configurable tooltip to Custom Command plugin

- plugin-taskbar/lxqttaskgroup.cpp
Fixes https://github.com/lxqt/lxqt-panel/issues/2213
> Fixed regression in showing only task buttons of current screen

- plugin-customcommand/CMakeLists.txt
- plugin-customcommand/colorLabel.cpp
- plugin-customcommand/colorLabel.h
- plugin-customcommand/lxqtcustomcommand.cpp
- plugin-customcommand/lxqtcustomcommandconfiguration.cpp
- plugin-customcommand/lxqtcustomcommandconfiguration.h
- plugin-customcommand/lxqtcustomcommandconfiguration.ui
Closes https://github.com/lxqt/lxqt-panel/issues/2220
> Added an option for text color of Custom Command

- panel/man/lxqt-panel.1
Preview: `man -l panel/man/lxqt-panel.1 `...
> Updated manpage

- panel/config/configplacement.cpp
> Desktop → Screen in dialog

- plugin-statusnotifier/sniasync.h
I tried (and succeded) to get all the known properties by org.freedesktop.DBus.Properties.GetAll on initialization and then just try to fetch from DBus object, if the property is "supported" by the object. But the properties can appear and/or disappear during the DBus object lifetime. So this solution would probably bring more hard to debug user complaints.
The cleanest way then would be to just ignore the UnknownProperty error. But some DBus StatusNotifierItem objects are even not responding with the org.freedesktop.DBus.Error.UnknownProperty error. So I added few more, which I have observed.
closes #2256
> statusnotifier: Don't write debug for "UnknownProperty" errors

- .ci/build.sh
- README.md
See the port to SNI in https://github.com/lxqt/lxqt-panel/pull/1721
> libxtst is now used instead of libxcomposite

- panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp
Also, I wasn't completely satisfied with how windows were restored after showing desktop on kwin_wayland: if the user was on an empty desktop, he would feel nothing on restoring them because the focus wouldn't be given to the top restored window. With the wlroots backend, the top window is focused automatically, such that the desktop is changed to it.
So, in this patch, I activated the top window on restoring, regardless of the active desktop (like in the wlroots backend), such that the user couldn't miss the restored window(s).
> Minimize children of a window with it on kwin_wayland

- panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp
For whatever reason (a minor bug?), kwin_wayland may demand attention on showing a child window that doesn't block its *active* parent, while an active window shouldn't demand attention.
This patch checks whether the parent or child is active and demands attention only if neither is.
Closes https://github.com/lxqt/lxqt-panel/issues/2278
> No attention demand for active parent-child pairs on kwin_wayland

- panel/backends/wayland/kwin_wayland/lxqtwmbackend_kwinwayland.cpp
- panel/backends/wayland/wlroots/lxqtwmbackend_wlr.cpp
- panel/lxqtpanelapplication.cpp
Also, added Niri to the compositors supported by the wlroots backend.
> Made searching for backend in EVs case-insensitive

- plugin-fancymenu/lxqtfancymenuappmodel.h
https://github.com/lxqt/lxqt-panel/issues/2253
> Squash mismatched tags warning

- plugin-statusnotifier/sniasync.h
> statusnotifier: Fix std::function<>::argument_type deprecation/removal

- plugin-networkmonitor/lxqtnetworkmonitorconfiguration.ui
Same as https://github.com/lxqt/lxqt-panel/pull/2333
> plugin-networkmonitor: Remove groupbox properties and AlignVCenter
